/**
 * Generate a JSR-publishable font module from a font file.
 *
 * Usage: deno task generate <id> <path/to/font.ttf>
 *
 * Reads the font's own `name` table to determine its family — no family
 * string needs to be typed by hand — base64-embeds its bytes, and writes
 * `<id>.ts` next to this script. Only plain TrueType/OpenType (sfnt) files
 * are supported directly (including `.ttc` collections, whose first face is
 * used for the family label); WOFF/WOFF2 sources should be decompressed to
 * `.ttf`/`.otf` first.
 *
 * After running, add `"./<id>": "./<id>.ts"` to this package's `deno.jsonc`
 * `exports` map — JSR requires each subpath to be listed explicitly.
 */

const NAME_ID_FAMILY = 1;
const NAME_ID_TYPOGRAPHIC_FAMILY = 16;
const TTC_TAG = 0x74746366; // 'ttcf'

function readU16(view: DataView, offset: number): number {
  return view.getUint16(offset, false);
}

function readU32(view: DataView, offset: number): number {
  return view.getUint32(offset, false);
}

function readTag(view: DataView, offset: number): string {
  return String.fromCharCode(
    view.getUint8(offset),
    view.getUint8(offset + 1),
    view.getUint8(offset + 2),
    view.getUint8(offset + 3),
  );
}

/** Byte offset of the sfnt table directory for the font's first face. */
function sfntStart(view: DataView): number {
  // A `.ttc` collection header points at each face's own sfnt offset table;
  // we only need one face to label the family, so always use the first.
  return readU32(view, 0) === TTC_TAG ? readU32(view, 12) : 0;
}

function findTable(view: DataView, sfntOffset: number, tag: string): number | undefined {
  const numTables = readU16(view, sfntOffset + 4);
  const dirStart = sfntOffset + 12;
  for (let i = 0; i < numTables; i++) {
    const recordStart = dirStart + i * 16;
    if (readTag(view, recordStart) === tag) return readU32(view, recordStart + 8);
  }
  return undefined;
}

/** Platform 1 (Macintosh) records are ASCII/Mac-Roman; 0 and 3 are UTF-16BE. */
function decodeNameRecord(view: DataView, platformId: number, start: number, length: number): string {
  if (platformId === 1) {
    let value = "";
    for (let i = 0; i < length; i++) value += String.fromCharCode(view.getUint8(start + i));
    return value;
  }
  let value = "";
  for (let i = 0; i + 1 < length; i += 2) value += String.fromCharCode(readU16(view, start + i));
  return value;
}

/**
 * Read a font's family name from its own `name` table: the Typographic
 * Family (nameID 16) if present, else the plain Family (nameID 1) — the
 * same pair `blitz_dom`'s font loading falls back to when no override is
 * given, so a generated module's label always matches what CSS would
 * actually resolve to.
 */
export function readFamilyName(bytes: Uint8Array): string {
  const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
  const nameTableOffset = findTable(view, sfntStart(view), "name");
  if (nameTableOffset === undefined) {
    throw new Error("No `name` table found — is this a valid TTF/OTF file?");
  }

  const count = readU16(view, nameTableOffset + 2);
  const stringAreaStart = nameTableOffset + readU16(view, nameTableOffset + 4);

  let family: string | undefined;
  let typographicFamily: string | undefined;
  for (let i = 0; i < count; i++) {
    const recordStart = nameTableOffset + 6 + i * 12;
    const platformId = readU16(view, recordStart);
    const nameId = readU16(view, recordStart + 6);
    const length = readU16(view, recordStart + 8);
    const offset = readU16(view, recordStart + 10);
    if (nameId !== NAME_ID_FAMILY && nameId !== NAME_ID_TYPOGRAPHIC_FAMILY) continue;

    const value = decodeNameRecord(view, platformId, stringAreaStart + offset, length);
    if (nameId === NAME_ID_TYPOGRAPHIC_FAMILY) typographicFamily ??= value;
    else family ??= value;
  }

  const result = typographicFamily ?? family;
  if (!result) {
    throw new Error("Font has no Family (nameID 1) or Typographic Family (nameID 16) entry");
  }
  return result;
}

function moduleSource(sourcePath: string, family: string, base64: string): string {
  return `// Generated by \`deno task generate\` from ${sourcePath}.
// Do not edit by hand — regenerate with \`deno task generate\` instead.

import type { FontModule } from "./types.ts";

const data: Uint8Array = Uint8Array.fromBase64(
  "${base64}",
);

const font: FontModule = { family: "${family}", data };
export default font;
`;
}

if (import.meta.main) {
  const [id, fontPath] = Deno.args;
  if (!id || !fontPath) {
    console.error("Usage: deno task generate <id> <path/to/font.ttf>");
    Deno.exit(1);
  }

  const bytes = await Deno.readFile(fontPath);
  const family = readFamilyName(bytes);
  const base64 = bytes.toBase64();
  const outUrl = new URL(`./${id}.ts`, import.meta.url);
  await Deno.writeTextFile(outUrl, moduleSource(fontPath, family, base64));

  console.log(`wrote ${id}.ts — family "${family}", ${bytes.length} bytes`);
  console.log(`If this is a new font, add it to this package's deno.jsonc "exports":`);
  console.log(`  "./${id}": "./${id}.ts"`);
}
