import type { QuoxRenderer as WasmRenderer } from "../lib/quox.js";
import {
  assertFiniteNumber,
  assertIntegerRange,
  assertKnownMask,
  assertPositiveUint32,
  assertUint32,
} from "./ffi_numbers.ts";

export const DOM_DISPATCH_EVENT_TYPES = Object.freeze(
  [
    "pointermove",
    "pointerdown",
    "pointerup",
    "pointercancel",
    "pointerenter",
    "pointerleave",
    "pointerover",
    "pointerout",
    "mousemove",
    "mousedown",
    "mouseup",
    "mouseenter",
    "mouseleave",
    "mouseover",
    "mouseout",
    "scroll",
    "wheel",
    "click",
    "auxclick",
    "contextmenu",
    "dblclick",
    "keydown",
    "keyup",
    "copy",
    "cut",
    "paste",
    "beforeinput",
    "input",
    "change",
    "compositionstart",
    "compositionupdate",
    "compositionend",
    "focus",
    "blur",
    "focusin",
    "focusout",
  ] as const,
);

export type DomDispatchEventType = (typeof DOM_DISPATCH_EVENT_TYPES)[number];

export interface DomDispatchMousePayload {
  readonly clientX: number;
  readonly clientY: number;
  readonly pageX: number;
  readonly pageY: number;
  readonly screenX: number;
  readonly screenY: number;
  readonly offsetX: number;
  readonly offsetY: number;
  readonly movementX: number;
  readonly movementY: number;
  readonly button: number;
  readonly buttons: number;
  readonly detail: number;
  readonly shiftKey: boolean;
  readonly ctrlKey: boolean;
  readonly altKey: boolean;
  readonly metaKey: boolean;
  readonly capsLock: boolean;
  readonly altGraphKey: boolean;
  readonly fnKey: boolean;
  readonly numLock: boolean;
  readonly scrollLock: boolean;
  readonly relatedTarget: number | null;
}

export interface DomDispatchPointerPayload extends DomDispatchMousePayload {
  readonly pointerId: number;
  readonly pointerType: string;
  readonly isPrimary: boolean;
  readonly width: number;
  readonly height: number;
  readonly pressure: number;
  readonly tangentialPressure: number;
  readonly tiltX: number;
  readonly tiltY: number;
  readonly twist: number;
  readonly altitudeAngle: number;
  readonly azimuthAngle: number;
  readonly persistentDeviceId: number;
}

export interface DomDispatchWheelPayload extends DomDispatchMousePayload {
  readonly deltaX: number;
  readonly deltaY: number;
  readonly deltaZ: number;
  readonly deltaMode: number;
}

export interface DomDispatchKeyboardPayload {
  readonly key: string;
  readonly code: string;
  readonly location: number;
  readonly repeat: boolean;
  readonly isComposing: boolean;
  readonly keyCode: number;
  readonly shiftKey: boolean;
  readonly ctrlKey: boolean;
  readonly altKey: boolean;
  readonly metaKey: boolean;
  readonly capsLock: boolean;
  readonly altGraphKey: boolean;
  readonly fnKey: boolean;
  readonly numLock: boolean;
  readonly scrollLock: boolean;
}

export interface DomDispatchClipboardPayload {
  /** Plaintext clipboard contents. Copy and cut expose an empty transfer as `null`. */
  readonly text: string | null;
}

export interface DomDispatchInputPayload {
  readonly data: string | null;
  readonly inputType: string;
  readonly isComposing: boolean;
}

export interface DomDispatchCompositionPayload {
  readonly data: string;
}

export interface DomDispatchFocusPayload {
  readonly relatedTarget: number | null;
}

export type DomDispatchEventPayload =
  | DomDispatchMousePayload
  | DomDispatchPointerPayload
  | DomDispatchWheelPayload
  | DomDispatchKeyboardPayload
  | DomDispatchClipboardPayload
  | DomDispatchInputPayload
  | DomDispatchCompositionPayload
  | DomDispatchFocusPayload;

export interface DomDispatchEventStep<Payload = DomDispatchEventPayload> {
  readonly kind: "event";
  readonly frameId: number;
  readonly eventId: number;
  readonly type: DomDispatchEventType;
  readonly target: number;
  /** Target-first propagation path, frozen before it crosses the renderer boundary. */
  readonly path: readonly number[];
  readonly bubbles: boolean;
  readonly cancelable: boolean;
  readonly composed: boolean;
  readonly timeStamp: number;
  readonly payload?: Payload;
}

export interface DomDispatchCompleteStep {
  readonly kind: "complete";
  readonly frameId: number;
  readonly redrawRequested: boolean;
}

export type DomDispatchStep<Payload = DomDispatchEventPayload> =
  | DomDispatchEventStep<Payload>
  | DomDispatchCompleteStep;

/** A malformed initial step whose independently inspected frame ID can still be aborted. */
export class DomDispatchInitialStepError extends Error {
  readonly frameId: number;
  readonly validationError: unknown;

  constructor(frameId: number, validationError: unknown) {
    super("quox: the renderer returned a malformed initial DOM dispatch step", {
      cause: validationError,
    });
    this.name = "DomDispatchInitialStepError";
    this.frameId = frameId;
    this.validationError = validationError;
  }
}

/**
 * Structural view of the staged methods generated by wasm-bindgen.
 *
 * The checked-in generated declaration can lag the Rust source, so the renderer is cast to this
 * interface once at the boundary. Return values deliberately remain `unknown` until validated.
 */
export interface DomDispatchRendererSource {
  begin_stationary_pointer_refresh(): unknown;
  begin_pointer_move(
    x: number,
    y: number,
    screenKnown: boolean,
    screenX: number,
    screenY: number,
    buttons: number,
    modifierBits: number,
    timeStamp: number,
  ): unknown;
  begin_pointer_cancel(
    x: number,
    y: number,
    screenKnown: boolean,
    screenX: number,
    screenY: number,
    canceledButtons: number,
    modifierBits: number,
    timeStamp: number,
  ): unknown;
  begin_pointer_enter(
    x: number,
    y: number,
    screenKnown: boolean,
    screenX: number,
    screenY: number,
    buttons: number,
    modifierBits: number,
    timeStamp: number,
  ): unknown;
  begin_pointer_leave(
    x: number,
    y: number,
    screenKnown: boolean,
    screenX: number,
    screenY: number,
    buttons: number,
    modifierBits: number,
    timeStamp: number,
  ): unknown;
  begin_pointer_down(
    x: number,
    y: number,
    screenKnown: boolean,
    screenX: number,
    screenY: number,
    button: number,
    buttons: number,
    modifierBits: number,
    timeStamp: number,
    detail: number,
  ): unknown;
  begin_pointer_up(
    x: number,
    y: number,
    screenKnown: boolean,
    screenX: number,
    screenY: number,
    button: number,
    buttons: number,
    modifierBits: number,
    timeStamp: number,
    detail: number,
  ): unknown;
  begin_wheel(
    x: number,
    y: number,
    screenKnown: boolean,
    screenX: number,
    screenY: number,
    blitzDeltaX: number,
    blitzDeltaY: number,
    deltaX: number,
    deltaY: number,
    deltaMode: number,
    buttons: number,
    modifierBits: number,
    timeStamp: number,
  ): unknown;
  begin_key_event(
    code: string,
    key: string,
    keycode: number,
    modifierBits: number,
    location: number,
    eventFlags: number,
    sourceKeyInputId?: number,
  ): unknown;
  begin_focus(nodeHandle: number): unknown;
  begin_blur(nodeHandle: number): unknown;
  begin_apple_standard_keybinding(command: string, sourceKeyInputId?: number): unknown;
  begin_ime_enabled(): unknown;
  begin_ime_disabled(): unknown;
  begin_ime_preedit(text: string, cursorStart?: number, cursorEnd?: number): unknown;
  begin_ime_commit(text: string, sourceKeyInputId?: number): unknown;
  begin_ime_delete_surrounding(beforeBytes: number, afterBytes: number): unknown;
  resume_dom_dispatch(frameId: number, eventId: number, defaultPrevented: boolean): unknown;
  abort_dom_dispatch(frameId: number): boolean;
}

const supportedEventTypes: ReadonlySet<string> = new Set(DOM_DISPATCH_EVENT_TYPES);

type OwnPropertyDescriptors = ReturnType<typeof Object.getOwnPropertyDescriptors>;

function dataDescriptor(
  descriptors: OwnPropertyDescriptors,
  property: PropertyKey,
  context: string,
): PropertyDescriptor {
  const entry = Object.getOwnPropertyDescriptor(descriptors, property);
  if (entry === undefined || !("value" in entry)) {
    throw new TypeError(`quox: ${context} must be an own data property`);
  }
  return entry.value as PropertyDescriptor;
}

function inspectPlainRecord(value: unknown, context: string): OwnPropertyDescriptors {
  if (typeof value !== "object" || value === null) {
    throw new TypeError(`quox: ${context} must be a plain object`);
  }

  const prototype = Object.getPrototypeOf(value);
  if (prototype !== Object.prototype && prototype !== null) {
    throw new TypeError(`quox: ${context} must be a plain object`);
  }

  const descriptors = Object.getOwnPropertyDescriptors(value);
  for (const property of Reflect.ownKeys(descriptors)) {
    const descriptor = dataDescriptor(descriptors, property, `${context}.${String(property)}`);
    if (!("value" in descriptor)) {
      throw new TypeError(`quox: ${context}.${String(property)} must not be an accessor`);
    }
  }
  return descriptors;
}

function inspectExactPlainRecord(
  value: unknown,
  context: string,
  properties: readonly string[],
): OwnPropertyDescriptors {
  const descriptors = inspectPlainRecord(value, context);
  assertExactProperties(descriptors, context, properties);
  return descriptors;
}

function assertExactProperties(
  descriptors: OwnPropertyDescriptors,
  context: string,
  properties: readonly string[],
): void {
  const expected = new Set<PropertyKey>(properties);
  for (const property of Reflect.ownKeys(descriptors)) {
    if (!expected.has(property)) {
      throw new TypeError(`quox: ${context}.${String(property)} is not a supported property`);
    }
  }
  for (const property of properties) requiredValue(descriptors, property, context);
}

function requiredValue(
  descriptors: OwnPropertyDescriptors,
  property: PropertyKey,
  context: string,
): unknown {
  const descriptor = dataDescriptor(descriptors, property, `${context}.${String(property)}`);
  if (!("value" in descriptor)) {
    throw new TypeError(`quox: ${context}.${String(property)} must not be an accessor`);
  }
  return descriptor.value;
}

function assertBoolean(value: unknown, name: string): boolean {
  if (typeof value !== "boolean") {
    throw new TypeError(`quox: ${name} must be a boolean`);
  }
  return value;
}

function assertString(value: unknown, name: string): string {
  if (typeof value !== "string") {
    throw new TypeError(`quox: ${name} must be a string`);
  }
  return value;
}

function assertNullableNodeHandle(value: unknown, name: string): number | null {
  return value === null ? null : assertPositiveUint32(value, name);
}

function assertFiniteRange(
  value: unknown,
  minimum: number,
  maximum: number,
  name: string,
): number {
  const number = assertFiniteNumber(value, name);
  if (number < minimum || number > maximum) {
    throw new RangeError(`quox: ${name} must be from ${minimum} through ${maximum}`);
  }
  return number;
}

function assertFiniteFloatRange(
  value: unknown,
  minimum: number,
  maximum: number,
  name: string,
): number {
  const number = assertFiniteRange(value, minimum, maximum, name);
  if (!Object.is(Math.fround(number), number)) {
    throw new RangeError(`quox: ${name} must be exactly representable as a 32-bit float`);
  }
  return number;
}

const MOUSE_PAYLOAD_PROPERTIES = Object.freeze(
  [
    "clientX",
    "clientY",
    "pageX",
    "pageY",
    "screenX",
    "screenY",
    "offsetX",
    "offsetY",
    "movementX",
    "movementY",
    "button",
    "buttons",
    "detail",
    "shiftKey",
    "ctrlKey",
    "altKey",
    "metaKey",
    "capsLock",
    "altGraphKey",
    "fnKey",
    "numLock",
    "scrollLock",
    "relatedTarget",
  ] as const,
);

const POINTER_PAYLOAD_PROPERTIES = Object.freeze(
  [
    ...MOUSE_PAYLOAD_PROPERTIES,
    "pointerId",
    "pointerType",
    "isPrimary",
    "width",
    "height",
    "pressure",
    "tangentialPressure",
    "tiltX",
    "tiltY",
    "twist",
    "altitudeAngle",
    "azimuthAngle",
    "persistentDeviceId",
  ] as const,
);

const WHEEL_PAYLOAD_PROPERTIES = Object.freeze(
  [
    ...MOUSE_PAYLOAD_PROPERTIES,
    "deltaX",
    "deltaY",
    "deltaZ",
    "deltaMode",
  ] as const,
);

const KEYBOARD_PAYLOAD_PROPERTIES = Object.freeze(
  [
    "key",
    "code",
    "location",
    "repeat",
    "isComposing",
    "keyCode",
    "shiftKey",
    "ctrlKey",
    "altKey",
    "metaKey",
    "capsLock",
    "altGraphKey",
    "fnKey",
    "numLock",
    "scrollLock",
  ] as const,
);

const CLIPBOARD_PAYLOAD_PROPERTIES = Object.freeze(["text"] as const);
const INPUT_PAYLOAD_PROPERTIES = Object.freeze(["data", "inputType", "isComposing"] as const);
const COMPOSITION_PAYLOAD_PROPERTIES = Object.freeze(["data"] as const);
const FOCUS_PAYLOAD_PROPERTIES = Object.freeze(["relatedTarget"] as const);
const COMPLETE_STEP_PROPERTIES = Object.freeze(["kind", "frameId", "redrawRequested"] as const);
const EVENT_STEP_PROPERTIES = Object.freeze(
  [
    "kind",
    "frameId",
    "eventId",
    "type",
    "target",
    "path",
    "bubbles",
    "cancelable",
    "composed",
    "timeStamp",
  ] as const,
);
const PAYLOAD_EVENT_STEP_PROPERTIES = Object.freeze([...EVENT_STEP_PROPERTIES, "payload"] as const);

function mousePayloadFields(descriptors: OwnPropertyDescriptors): DomDispatchMousePayload {
  const field = (name: string) => requiredValue(descriptors, name, "DOM dispatch payload");
  return {
    clientX: assertFiniteNumber(field("clientX"), "DOM dispatch payload.clientX"),
    clientY: assertFiniteNumber(field("clientY"), "DOM dispatch payload.clientY"),
    pageX: assertFiniteNumber(field("pageX"), "DOM dispatch payload.pageX"),
    pageY: assertFiniteNumber(field("pageY"), "DOM dispatch payload.pageY"),
    screenX: assertFiniteNumber(field("screenX"), "DOM dispatch payload.screenX"),
    screenY: assertFiniteNumber(field("screenY"), "DOM dispatch payload.screenY"),
    offsetX: assertFiniteNumber(field("offsetX"), "DOM dispatch payload.offsetX"),
    offsetY: assertFiniteNumber(field("offsetY"), "DOM dispatch payload.offsetY"),
    movementX: assertFiniteNumber(field("movementX"), "DOM dispatch payload.movementX"),
    movementY: assertFiniteNumber(field("movementY"), "DOM dispatch payload.movementY"),
    button: assertIntegerRange(field("button"), -1, 4, "DOM dispatch payload.button"),
    buttons: assertKnownMask(field("buttons"), 0x1f, "DOM dispatch payload.buttons"),
    detail: assertIntegerRange(
      field("detail"),
      0,
      0x7fff_ffff,
      "DOM dispatch payload.detail",
    ),
    shiftKey: assertBoolean(field("shiftKey"), "DOM dispatch payload.shiftKey"),
    ctrlKey: assertBoolean(field("ctrlKey"), "DOM dispatch payload.ctrlKey"),
    altKey: assertBoolean(field("altKey"), "DOM dispatch payload.altKey"),
    metaKey: assertBoolean(field("metaKey"), "DOM dispatch payload.metaKey"),
    capsLock: assertBoolean(field("capsLock"), "DOM dispatch payload.capsLock"),
    altGraphKey: assertBoolean(field("altGraphKey"), "DOM dispatch payload.altGraphKey"),
    fnKey: assertBoolean(field("fnKey"), "DOM dispatch payload.fnKey"),
    numLock: assertBoolean(field("numLock"), "DOM dispatch payload.numLock"),
    scrollLock: assertBoolean(field("scrollLock"), "DOM dispatch payload.scrollLock"),
    relatedTarget: assertNullableNodeHandle(
      field("relatedTarget"),
      "DOM dispatch payload.relatedTarget",
    ),
  };
}

function validateMousePayload(value: unknown): DomDispatchMousePayload {
  const descriptors = inspectExactPlainRecord(
    value,
    "DOM dispatch payload",
    MOUSE_PAYLOAD_PROPERTIES,
  );
  return Object.freeze(mousePayloadFields(descriptors));
}

function validatePointerPayload(value: unknown): DomDispatchPointerPayload {
  const descriptors = inspectExactPlainRecord(
    value,
    "DOM dispatch payload",
    POINTER_PAYLOAD_PROPERTIES,
  );
  const field = (name: string) => requiredValue(descriptors, name, "DOM dispatch payload");
  const width = assertFiniteNumber(field("width"), "DOM dispatch payload.width");
  const height = assertFiniteNumber(field("height"), "DOM dispatch payload.height");
  const azimuthAngle = assertFiniteRange(
    field("azimuthAngle"),
    0,
    Math.PI * 2,
    "DOM dispatch payload.azimuthAngle",
  );
  if (width < 0 || height < 0) {
    throw new RangeError("quox: DOM dispatch pointer width and height must be nonnegative");
  }
  return Object.freeze({
    ...mousePayloadFields(descriptors),
    pointerId: assertIntegerRange(
      field("pointerId"),
      -1,
      0x7fff_ffff,
      "DOM dispatch payload.pointerId",
    ),
    pointerType: assertString(field("pointerType"), "DOM dispatch payload.pointerType"),
    isPrimary: assertBoolean(field("isPrimary"), "DOM dispatch payload.isPrimary"),
    width,
    height,
    pressure: assertFiniteFloatRange(field("pressure"), 0, 1, "DOM dispatch payload.pressure"),
    tangentialPressure: assertFiniteFloatRange(
      field("tangentialPressure"),
      -1,
      1,
      "DOM dispatch payload.tangentialPressure",
    ),
    tiltX: assertIntegerRange(field("tiltX"), -90, 90, "DOM dispatch payload.tiltX"),
    tiltY: assertIntegerRange(field("tiltY"), -90, 90, "DOM dispatch payload.tiltY"),
    twist: assertIntegerRange(field("twist"), 0, 359, "DOM dispatch payload.twist"),
    altitudeAngle: assertFiniteRange(
      field("altitudeAngle"),
      0,
      Math.PI / 2,
      "DOM dispatch payload.altitudeAngle",
    ),
    azimuthAngle,
    persistentDeviceId: assertIntegerRange(
      field("persistentDeviceId"),
      0,
      0x7fff_ffff,
      "DOM dispatch payload.persistentDeviceId",
    ),
  });
}

function validateWheelPayload(value: unknown): DomDispatchWheelPayload {
  const descriptors = inspectExactPlainRecord(
    value,
    "DOM dispatch payload",
    WHEEL_PAYLOAD_PROPERTIES,
  );
  const field = (name: string) => requiredValue(descriptors, name, "DOM dispatch payload");
  return Object.freeze({
    ...mousePayloadFields(descriptors),
    deltaX: assertFiniteNumber(field("deltaX"), "DOM dispatch payload.deltaX"),
    deltaY: assertFiniteNumber(field("deltaY"), "DOM dispatch payload.deltaY"),
    deltaZ: assertFiniteNumber(field("deltaZ"), "DOM dispatch payload.deltaZ"),
    deltaMode: assertIntegerRange(field("deltaMode"), 0, 2, "DOM dispatch payload.deltaMode"),
  });
}

function validateKeyboardPayload(value: unknown): DomDispatchKeyboardPayload {
  const descriptors = inspectExactPlainRecord(
    value,
    "DOM dispatch payload",
    KEYBOARD_PAYLOAD_PROPERTIES,
  );
  const field = (name: string) => requiredValue(descriptors, name, "DOM dispatch payload");
  return Object.freeze({
    key: assertString(field("key"), "DOM dispatch payload.key"),
    code: assertString(field("code"), "DOM dispatch payload.code"),
    location: assertIntegerRange(field("location"), 0, 3, "DOM dispatch payload.location"),
    repeat: assertBoolean(field("repeat"), "DOM dispatch payload.repeat"),
    isComposing: assertBoolean(field("isComposing"), "DOM dispatch payload.isComposing"),
    keyCode: assertUint32(field("keyCode"), "DOM dispatch payload.keyCode"),
    shiftKey: assertBoolean(field("shiftKey"), "DOM dispatch payload.shiftKey"),
    ctrlKey: assertBoolean(field("ctrlKey"), "DOM dispatch payload.ctrlKey"),
    altKey: assertBoolean(field("altKey"), "DOM dispatch payload.altKey"),
    metaKey: assertBoolean(field("metaKey"), "DOM dispatch payload.metaKey"),
    capsLock: assertBoolean(field("capsLock"), "DOM dispatch payload.capsLock"),
    altGraphKey: assertBoolean(field("altGraphKey"), "DOM dispatch payload.altGraphKey"),
    fnKey: assertBoolean(field("fnKey"), "DOM dispatch payload.fnKey"),
    numLock: assertBoolean(field("numLock"), "DOM dispatch payload.numLock"),
    scrollLock: assertBoolean(field("scrollLock"), "DOM dispatch payload.scrollLock"),
  });
}

function validateClipboardPayload(
  value: unknown,
  type: "copy" | "cut" | "paste",
): DomDispatchClipboardPayload {
  const descriptors = inspectExactPlainRecord(
    value,
    "DOM dispatch payload",
    CLIPBOARD_PAYLOAD_PROPERTIES,
  );
  const text = requiredValue(descriptors, "text", "DOM dispatch payload");
  if (text !== null && typeof text !== "string") {
    throw new TypeError("quox: DOM dispatch payload.text must be a string or null");
  }
  if (type === "paste" && text === null) {
    throw new TypeError("quox: paste events require DOM dispatch payload.text to be a string");
  }
  if (type !== "paste" && text !== null) {
    throw new TypeError(`quox: ${type} events require DOM dispatch payload.text to be null`);
  }
  return Object.freeze({ text });
}

function validateInputPayload(value: unknown): DomDispatchInputPayload {
  const descriptors = inspectExactPlainRecord(
    value,
    "DOM dispatch payload",
    INPUT_PAYLOAD_PROPERTIES,
  );
  const field = (name: string) => requiredValue(descriptors, name, "DOM dispatch payload");
  const data = field("data");
  if (data !== null && typeof data !== "string") {
    throw new TypeError("quox: DOM dispatch payload.data must be a string or null");
  }
  return Object.freeze({
    data,
    inputType: assertString(field("inputType"), "DOM dispatch payload.inputType"),
    isComposing: assertBoolean(field("isComposing"), "DOM dispatch payload.isComposing"),
  });
}

function validateCompositionPayload(value: unknown): DomDispatchCompositionPayload {
  const descriptors = inspectExactPlainRecord(
    value,
    "DOM dispatch payload",
    COMPOSITION_PAYLOAD_PROPERTIES,
  );
  return Object.freeze({
    data: assertString(
      requiredValue(descriptors, "data", "DOM dispatch payload"),
      "DOM dispatch payload.data",
    ),
  });
}

function validateFocusPayload(value: unknown): DomDispatchFocusPayload {
  const descriptors = inspectExactPlainRecord(
    value,
    "DOM dispatch payload",
    FOCUS_PAYLOAD_PROPERTIES,
  );
  return Object.freeze({
    relatedTarget: assertNullableNodeHandle(
      requiredValue(descriptors, "relatedTarget", "DOM dispatch payload"),
      "DOM dispatch payload.relatedTarget",
    ),
  });
}

function validateEventPayload(
  type: DomDispatchEventType,
  present: boolean,
  value: unknown,
): DomDispatchEventPayload | undefined {
  if (type === "scroll" || type === "change" || (type === "input" && !present)) {
    if (present) throw new TypeError(`quox: ${type} events must not carry a payload`);
    return undefined;
  }
  if (!present) throw new TypeError(`quox: ${type} events must carry a payload`);

  switch (type) {
    case "pointermove":
    case "pointerdown":
    case "pointerup":
    case "pointercancel":
    case "pointerenter":
    case "pointerleave":
    case "pointerover":
    case "pointerout":
    case "click":
    case "auxclick":
    case "contextmenu":
      return validatePointerPayload(value);
    case "mousemove":
    case "mousedown":
    case "mouseup":
    case "mouseenter":
    case "mouseleave":
    case "mouseover":
    case "mouseout":
    case "dblclick":
      return validateMousePayload(value);
    case "wheel":
      return validateWheelPayload(value);
    case "keydown":
    case "keyup":
      return validateKeyboardPayload(value);
    case "copy":
    case "cut":
    case "paste":
      return validateClipboardPayload(value, type);
    case "beforeinput":
    case "input":
      return validateInputPayload(value);
    case "compositionstart":
    case "compositionupdate":
    case "compositionend":
      return validateCompositionPayload(value);
    case "focus":
    case "blur":
    case "focusin":
    case "focusout":
      return validateFocusPayload(value);
    default:
      return assertNever(type);
  }
}

function assertNever(value: never): never {
  throw new TypeError(`quox: unsupported DOM dispatch event type ${value}`);
}

function assertEventType(value: unknown): DomDispatchEventType {
  if (typeof value !== "string" || !supportedEventTypes.has(value)) {
    throw new TypeError("quox: DOM dispatch event type is unsupported");
  }
  return value as DomDispatchEventType;
}

const typedArrayPrototype = Object.getPrototypeOf(Uint32Array.prototype);
const typedArrayLengthGetter = Object.getOwnPropertyDescriptor(typedArrayPrototype, "length")?.get;

function typedArrayLength(value: Uint32Array): number {
  if (typedArrayLengthGetter === undefined) {
    throw new TypeError("quox: this runtime cannot inspect a Uint32Array path");
  }
  return Reflect.apply(typedArrayLengthGetter, value, []) as number;
}

function normalizeArrayPath(value: unknown[]): readonly number[] {
  if (Object.getPrototypeOf(value) !== Array.prototype) {
    throw new TypeError("quox: DOM dispatch path must be a plain array or Uint32Array");
  }

  const descriptors = Object.getOwnPropertyDescriptors(value);
  for (const property of Reflect.ownKeys(descriptors)) {
    const descriptor = dataDescriptor(descriptors, property, `DOM dispatch path.${String(property)}`);
    if (!("value" in descriptor)) {
      throw new TypeError(`quox: DOM dispatch path.${String(property)} must not be an accessor`);
    }
  }

  const lengthValue = requiredValue(descriptors, "length", "DOM dispatch path");
  if (!Number.isSafeInteger(lengthValue) || (lengthValue as number) <= 0) {
    throw new RangeError("quox: DOM dispatch path must not be empty");
  }

  const path: number[] = [];
  for (let index = 0; index < (lengthValue as number); index += 1) {
    path.push(
      assertPositiveUint32(
        requiredValue(descriptors, String(index), "DOM dispatch path"),
        `DOM dispatch path[${index}]`,
      ),
    );
  }
  return Object.freeze(path);
}

function normalizeUint32ArrayPath(value: Uint32Array): readonly number[] {
  if (Object.getPrototypeOf(value) !== Uint32Array.prototype) {
    throw new TypeError("quox: DOM dispatch path must be a plain array or Uint32Array");
  }

  const length = typedArrayLength(value);
  if (length === 0) {
    throw new RangeError("quox: DOM dispatch path must not be empty");
  }

  const path: number[] = [];
  for (let index = 0; index < length; index += 1) {
    const descriptor = Object.getOwnPropertyDescriptor(value, String(index));
    if (descriptor === undefined || !("value" in descriptor)) {
      throw new TypeError(`quox: DOM dispatch path[${index}] must be an own data property`);
    }
    path.push(assertPositiveUint32(descriptor.value, `DOM dispatch path[${index}]`));
  }
  return Object.freeze(path);
}

function normalizePath(value: unknown): readonly number[] {
  if (Array.isArray(value)) return normalizeArrayPath(value);
  if (ArrayBuffer.isView(value) && Object.getPrototypeOf(value) === Uint32Array.prototype) {
    return normalizeUint32ArrayPath(value as Uint32Array);
  }
  throw new TypeError("quox: DOM dispatch path must be a plain array or Uint32Array");
}

function recoverInitialFrameId(value: unknown): number | undefined {
  try {
    if (typeof value !== "object" || value === null) return undefined;
    const prototype = Object.getPrototypeOf(value);
    if (prototype !== Object.prototype && prototype !== null) return undefined;
    const descriptor = Object.getOwnPropertyDescriptor(value, "frameId");
    if (descriptor === undefined || !("value" in descriptor)) return undefined;
    return assertPositiveUint32(descriptor.value, "DOM dispatch frameId");
  } catch {
    return undefined;
  }
}

/** Validate an untrusted plain step object returned across the WASM boundary. */
export function validateDomDispatchStep(value: unknown): DomDispatchStep {
  const descriptors = inspectPlainRecord(value, "DOM dispatch step");
  const kind = requiredValue(descriptors, "kind", "DOM dispatch step");
  const frameId = assertPositiveUint32(
    requiredValue(descriptors, "frameId", "DOM dispatch step"),
    "DOM dispatch frameId",
  );

  if (kind === "complete") {
    assertExactProperties(descriptors, "DOM dispatch step", COMPLETE_STEP_PROPERTIES);
    return Object.freeze({
      kind,
      frameId,
      redrawRequested: assertBoolean(
        requiredValue(descriptors, "redrawRequested", "DOM dispatch step"),
        "DOM dispatch redrawRequested",
      ),
    });
  }
  if (kind !== "event") {
    throw new TypeError('quox: DOM dispatch step kind must be "event" or "complete"');
  }

  const type = assertEventType(requiredValue(descriptors, "type", "DOM dispatch step"));
  const payloadDescriptor = Object.getOwnPropertyDescriptor(descriptors, "payload");
  const payloadless = type === "scroll" || type === "change" || (type === "input" && payloadDescriptor === undefined);
  assertExactProperties(
    descriptors,
    "DOM dispatch step",
    payloadless ? EVENT_STEP_PROPERTIES : PAYLOAD_EVENT_STEP_PROPERTIES,
  );

  const target = assertPositiveUint32(
    requiredValue(descriptors, "target", "DOM dispatch step"),
    "DOM dispatch target",
  );
  const path = normalizePath(requiredValue(descriptors, "path", "DOM dispatch step"));
  if (path[0] !== target) {
    throw new RangeError("quox: DOM dispatch path must begin with its target");
  }

  const payload = validateEventPayload(
    type,
    payloadDescriptor !== undefined,
    payloadDescriptor === undefined ? undefined : requiredValue(descriptors, "payload", "DOM dispatch step"),
  );

  const timeStamp = assertFiniteNumber(
    requiredValue(descriptors, "timeStamp", "DOM dispatch step"),
    "DOM dispatch timeStamp",
  );
  if (timeStamp < 0) {
    throw new RangeError("quox: DOM dispatch timeStamp must be nonnegative");
  }

  const step: DomDispatchEventStep = {
    kind,
    frameId,
    eventId: assertPositiveUint32(
      requiredValue(descriptors, "eventId", "DOM dispatch step"),
      "DOM dispatch eventId",
    ),
    type,
    target,
    path,
    bubbles: assertBoolean(
      requiredValue(descriptors, "bubbles", "DOM dispatch step"),
      "DOM dispatch bubbles",
    ),
    cancelable: assertBoolean(
      requiredValue(descriptors, "cancelable", "DOM dispatch step"),
      "DOM dispatch cancelable",
    ),
    composed: assertBoolean(
      requiredValue(descriptors, "composed", "DOM dispatch step"),
      "DOM dispatch composed",
    ),
    timeStamp,
  };

  return payload === undefined ? Object.freeze(step) : Object.freeze({ ...step, payload });
}

/** Typed and validated adapter over the staged methods absent from stale generated declarations. */
export class DomDispatchRendererPort {
  readonly #renderer: DomDispatchRendererSource;

  constructor(renderer: WasmRenderer | DomDispatchRendererSource) {
    this.#renderer = renderer as DomDispatchRendererSource;
  }

  #validateInitial(value: unknown): DomDispatchStep {
    try {
      return validateDomDispatchStep(value);
    } catch (error) {
      const frameId = recoverInitialFrameId(value);
      if (frameId === undefined) throw error;
      throw new DomDispatchInitialStepError(frameId, error);
    }
  }

  beginStationaryPointerRefresh(): DomDispatchStep {
    return this.#validateInitial(this.#renderer.begin_stationary_pointer_refresh());
  }

  beginPointerMove(
    x: number,
    y: number,
    screenKnown: boolean,
    screenX: number,
    screenY: number,
    buttons: number,
    modifierBits: number,
    timeStamp: number,
  ): DomDispatchStep {
    return this.#validateInitial(
      this.#renderer.begin_pointer_move(
        x,
        y,
        screenKnown,
        screenX,
        screenY,
        buttons,
        modifierBits,
        timeStamp,
      ),
    );
  }

  beginPointerCancel(
    x: number,
    y: number,
    screenKnown: boolean,
    screenX: number,
    screenY: number,
    canceledButtons: number,
    modifierBits: number,
    timeStamp: number,
  ): DomDispatchStep {
    return this.#validateInitial(
      this.#renderer.begin_pointer_cancel(
        x,
        y,
        screenKnown,
        screenX,
        screenY,
        canceledButtons,
        modifierBits,
        timeStamp,
      ),
    );
  }

  beginPointerEnter(
    x: number,
    y: number,
    screenKnown: boolean,
    screenX: number,
    screenY: number,
    buttons: number,
    modifierBits: number,
    timeStamp: number,
  ): DomDispatchStep {
    return this.#validateInitial(
      this.#renderer.begin_pointer_enter(
        x,
        y,
        screenKnown,
        screenX,
        screenY,
        buttons,
        modifierBits,
        timeStamp,
      ),
    );
  }

  beginPointerLeave(
    x: number,
    y: number,
    screenKnown: boolean,
    screenX: number,
    screenY: number,
    buttons: number,
    modifierBits: number,
    timeStamp: number,
  ): DomDispatchStep {
    return this.#validateInitial(
      this.#renderer.begin_pointer_leave(
        x,
        y,
        screenKnown,
        screenX,
        screenY,
        buttons,
        modifierBits,
        timeStamp,
      ),
    );
  }

  beginPointerDown(
    x: number,
    y: number,
    screenKnown: boolean,
    screenX: number,
    screenY: number,
    button: number,
    buttons: number,
    modifierBits: number,
    timeStamp: number,
    detail: number,
  ): DomDispatchStep {
    return this.#validateInitial(
      this.#renderer.begin_pointer_down(
        x,
        y,
        screenKnown,
        screenX,
        screenY,
        button,
        buttons,
        modifierBits,
        timeStamp,
        detail,
      ),
    );
  }

  beginPointerUp(
    x: number,
    y: number,
    screenKnown: boolean,
    screenX: number,
    screenY: number,
    button: number,
    buttons: number,
    modifierBits: number,
    timeStamp: number,
    detail: number,
  ): DomDispatchStep {
    return this.#validateInitial(
      this.#renderer.begin_pointer_up(
        x,
        y,
        screenKnown,
        screenX,
        screenY,
        button,
        buttons,
        modifierBits,
        timeStamp,
        detail,
      ),
    );
  }

  beginWheel(
    x: number,
    y: number,
    screenKnown: boolean,
    screenX: number,
    screenY: number,
    blitzDeltaX: number,
    blitzDeltaY: number,
    deltaX: number,
    deltaY: number,
    deltaMode: number,
    buttons: number,
    modifierBits: number,
    timeStamp: number,
  ): DomDispatchStep {
    return this.#validateInitial(
      this.#renderer.begin_wheel(
        x,
        y,
        screenKnown,
        screenX,
        screenY,
        blitzDeltaX,
        blitzDeltaY,
        deltaX,
        deltaY,
        deltaMode,
        buttons,
        modifierBits,
        timeStamp,
      ),
    );
  }

  beginKeyEvent(
    code: string,
    key: string,
    keycode: number,
    modifierBits: number,
    location: number,
    eventFlags: number,
    sourceKeyInputId?: number,
  ): DomDispatchStep {
    sourceKeyInputId = sourceKeyInputId === undefined
      ? undefined
      : assertPositiveUint32(sourceKeyInputId, "sourceKeyInputId");
    return this.#validateInitial(
      this.#renderer.begin_key_event(
        code,
        key,
        keycode,
        modifierBits,
        location,
        eventFlags,
        sourceKeyInputId,
      ),
    );
  }

  beginFocus(nodeHandle: number): DomDispatchStep {
    return this.#validateInitial(this.#renderer.begin_focus(assertUint32(nodeHandle, "nodeHandle")));
  }

  beginBlur(nodeHandle: number): DomDispatchStep {
    return this.#validateInitial(this.#renderer.begin_blur(assertUint32(nodeHandle, "nodeHandle")));
  }

  beginAppleStandardKeybinding(command: string, sourceKeyInputId?: number): DomDispatchStep {
    sourceKeyInputId = sourceKeyInputId === undefined
      ? undefined
      : assertPositiveUint32(sourceKeyInputId, "sourceKeyInputId");
    return this.#validateInitial(
      this.#renderer.begin_apple_standard_keybinding(command, sourceKeyInputId),
    );
  }

  beginImeEnabled(): DomDispatchStep {
    return this.#validateInitial(this.#renderer.begin_ime_enabled());
  }

  beginImeDisabled(): DomDispatchStep {
    return this.#validateInitial(this.#renderer.begin_ime_disabled());
  }

  beginImePreedit(text: string, cursorStart?: number, cursorEnd?: number): DomDispatchStep {
    return this.#validateInitial(
      this.#renderer.begin_ime_preedit(text, cursorStart, cursorEnd),
    );
  }

  beginImeCommit(text: string, sourceKeyInputId?: number): DomDispatchStep {
    sourceKeyInputId = sourceKeyInputId === undefined
      ? undefined
      : assertPositiveUint32(sourceKeyInputId, "sourceKeyInputId");
    return this.#validateInitial(this.#renderer.begin_ime_commit(text, sourceKeyInputId));
  }

  beginImeDeleteSurrounding(beforeBytes: number, afterBytes: number): DomDispatchStep {
    return this.#validateInitial(
      this.#renderer.begin_ime_delete_surrounding(beforeBytes, afterBytes),
    );
  }

  resumeDomDispatch(
    frameId: number,
    eventId: number,
    defaultPrevented: boolean,
  ): DomDispatchStep {
    frameId = assertPositiveUint32(frameId, "DOM dispatch frameId");
    eventId = assertPositiveUint32(eventId, "DOM dispatch eventId");
    defaultPrevented = assertBoolean(defaultPrevented, "DOM dispatch defaultPrevented");
    const step = validateDomDispatchStep(
      this.#renderer.resume_dom_dispatch(frameId, eventId, defaultPrevented),
    );
    if (step.frameId !== frameId) {
      throw new RangeError("quox: resumed DOM dispatch step belongs to a different frame");
    }
    return step;
  }

  abortDomDispatch(frameId: number): boolean {
    const redrawRequested = this.#renderer.abort_dom_dispatch(
      assertPositiveUint32(frameId, "DOM dispatch frameId"),
    );
    return assertBoolean(redrawRequested, "DOM dispatch abort redrawRequested");
  }
}
