import type { QuoxRenderer as WasmRenderer } from "../lib/quox.js";
import { assertFiniteNumber, assertPositiveUint32 } from "./ffi_numbers.ts";

export const DOM_DISPATCH_EVENT_TYPES = Object.freeze(
  [
    "pointermove",
    "pointerdown",
    "pointerup",
    "pointerenter",
    "pointerleave",
    "pointerover",
    "pointerout",
    "mousemove",
    "mousedown",
    "mouseup",
    "mouseenter",
    "mouseleave",
    "mouseover",
    "mouseout",
    "scroll",
    "wheel",
    "click",
    "contextmenu",
    "dblclick",
    "keypress",
    "keydown",
    "keyup",
    "input",
    "focus",
    "blur",
    "focusin",
    "focusout",
  ] as const,
);

export type DomDispatchEventType = (typeof DOM_DISPATCH_EVENT_TYPES)[number];

export interface DomDispatchEventStep<Payload = unknown> {
  readonly kind: "event";
  readonly frameId: number;
  readonly eventId: number;
  readonly type: DomDispatchEventType;
  readonly target: number;
  /** Target-first propagation path, frozen before it crosses the renderer boundary. */
  readonly path: readonly number[];
  readonly bubbles: boolean;
  readonly cancelable: boolean;
  readonly composed: boolean;
  readonly timeStamp: number;
  /** Reserved for the event-specific data added by D-04. */
  readonly payload?: Payload;
}

export interface DomDispatchCompleteStep {
  readonly kind: "complete";
  readonly frameId: number;
  readonly redrawRequested: boolean;
}

export type DomDispatchStep<Payload = unknown> =
  | DomDispatchEventStep<Payload>
  | DomDispatchCompleteStep;

/** A malformed initial step whose independently inspected frame ID can still be aborted. */
export class DomDispatchInitialStepError extends Error {
  readonly frameId: number;
  readonly validationError: unknown;

  constructor(frameId: number, validationError: unknown) {
    super("quox: the renderer returned a malformed initial DOM dispatch step", {
      cause: validationError,
    });
    this.name = "DomDispatchInitialStepError";
    this.frameId = frameId;
    this.validationError = validationError;
  }
}

/**
 * Structural view of the staged methods generated by wasm-bindgen.
 *
 * The checked-in generated declaration can lag the Rust source, so the renderer is cast to this
 * interface once at the boundary. Return values deliberately remain `unknown` until validated.
 */
export interface DomDispatchRendererSource {
  begin_pointer_move(
    x: number,
    y: number,
    buttons: number,
    modifierBits: number,
    timeStamp: number,
  ): unknown;
  begin_pointer_down(
    x: number,
    y: number,
    button: number,
    buttons: number,
    modifierBits: number,
    timeStamp: number,
    detail: number,
  ): unknown;
  begin_pointer_up(
    x: number,
    y: number,
    button: number,
    buttons: number,
    modifierBits: number,
    timeStamp: number,
    detail: number,
  ): unknown;
  begin_wheel(
    x: number,
    y: number,
    blitzDeltaX: number,
    blitzDeltaY: number,
    deltaX: number,
    deltaY: number,
    deltaMode: number,
    buttons: number,
    modifierBits: number,
    timeStamp: number,
  ): unknown;
  begin_key_event(
    code: string,
    key: string,
    keycode: number,
    modifierBits: number,
    location: number,
    eventFlags: number,
  ): unknown;
  begin_apple_standard_keybinding(command: string): unknown;
  begin_ime_enabled(): unknown;
  begin_ime_disabled(): unknown;
  begin_ime_preedit(text: string, cursorStart?: number, cursorEnd?: number): unknown;
  begin_ime_commit(text: string): unknown;
  begin_ime_delete_surrounding(beforeBytes: number, afterBytes: number): unknown;
  resume_dom_dispatch(frameId: number, eventId: number, defaultPrevented: boolean): unknown;
  abort_dom_dispatch(frameId: number): boolean;
}

const supportedEventTypes: ReadonlySet<string> = new Set(DOM_DISPATCH_EVENT_TYPES);

type OwnPropertyDescriptors = ReturnType<typeof Object.getOwnPropertyDescriptors>;

function dataDescriptor(
  descriptors: OwnPropertyDescriptors,
  property: PropertyKey,
  context: string,
): PropertyDescriptor {
  const entry = Object.getOwnPropertyDescriptor(descriptors, property);
  if (entry === undefined || !("value" in entry)) {
    throw new TypeError(`quox: ${context} must be an own data property`);
  }
  return entry.value as PropertyDescriptor;
}

function inspectPlainRecord(value: unknown, context: string): OwnPropertyDescriptors {
  if (typeof value !== "object" || value === null) {
    throw new TypeError(`quox: ${context} must be a plain object`);
  }

  const prototype = Object.getPrototypeOf(value);
  if (prototype !== Object.prototype && prototype !== null) {
    throw new TypeError(`quox: ${context} must be a plain object`);
  }

  const descriptors = Object.getOwnPropertyDescriptors(value);
  for (const property of Reflect.ownKeys(descriptors)) {
    const descriptor = dataDescriptor(descriptors, property, `${context}.${String(property)}`);
    if (!("value" in descriptor)) {
      throw new TypeError(`quox: ${context}.${String(property)} must not be an accessor`);
    }
  }
  return descriptors;
}

function requiredValue(
  descriptors: OwnPropertyDescriptors,
  property: PropertyKey,
  context: string,
): unknown {
  const descriptor = dataDescriptor(descriptors, property, `${context}.${String(property)}`);
  if (!("value" in descriptor)) {
    throw new TypeError(`quox: ${context}.${String(property)} must not be an accessor`);
  }
  return descriptor.value;
}

function assertBoolean(value: unknown, name: string): boolean {
  if (typeof value !== "boolean") {
    throw new TypeError(`quox: ${name} must be a boolean`);
  }
  return value;
}

function assertEventType(value: unknown): DomDispatchEventType {
  if (typeof value !== "string" || !supportedEventTypes.has(value)) {
    throw new TypeError("quox: DOM dispatch event type is unsupported");
  }
  return value as DomDispatchEventType;
}

const typedArrayPrototype = Object.getPrototypeOf(Uint32Array.prototype);
const typedArrayLengthGetter = Object.getOwnPropertyDescriptor(typedArrayPrototype, "length")?.get;

function typedArrayLength(value: Uint32Array): number {
  if (typedArrayLengthGetter === undefined) {
    throw new TypeError("quox: this runtime cannot inspect a Uint32Array path");
  }
  return Reflect.apply(typedArrayLengthGetter, value, []) as number;
}

function normalizeArrayPath(value: unknown[]): readonly number[] {
  if (Object.getPrototypeOf(value) !== Array.prototype) {
    throw new TypeError("quox: DOM dispatch path must be a plain array or Uint32Array");
  }

  const descriptors = Object.getOwnPropertyDescriptors(value);
  for (const property of Reflect.ownKeys(descriptors)) {
    const descriptor = dataDescriptor(descriptors, property, `DOM dispatch path.${String(property)}`);
    if (!("value" in descriptor)) {
      throw new TypeError(`quox: DOM dispatch path.${String(property)} must not be an accessor`);
    }
  }

  const lengthValue = requiredValue(descriptors, "length", "DOM dispatch path");
  if (!Number.isSafeInteger(lengthValue) || (lengthValue as number) <= 0) {
    throw new RangeError("quox: DOM dispatch path must not be empty");
  }

  const path: number[] = [];
  for (let index = 0; index < (lengthValue as number); index += 1) {
    path.push(
      assertPositiveUint32(
        requiredValue(descriptors, String(index), "DOM dispatch path"),
        `DOM dispatch path[${index}]`,
      ),
    );
  }
  return Object.freeze(path);
}

function normalizeUint32ArrayPath(value: Uint32Array): readonly number[] {
  if (Object.getPrototypeOf(value) !== Uint32Array.prototype) {
    throw new TypeError("quox: DOM dispatch path must be a plain array or Uint32Array");
  }

  const length = typedArrayLength(value);
  if (length === 0) {
    throw new RangeError("quox: DOM dispatch path must not be empty");
  }

  const path: number[] = [];
  for (let index = 0; index < length; index += 1) {
    const descriptor = Object.getOwnPropertyDescriptor(value, String(index));
    if (descriptor === undefined || !("value" in descriptor)) {
      throw new TypeError(`quox: DOM dispatch path[${index}] must be an own data property`);
    }
    path.push(assertPositiveUint32(descriptor.value, `DOM dispatch path[${index}]`));
  }
  return Object.freeze(path);
}

function normalizePath(value: unknown): readonly number[] {
  if (Array.isArray(value)) return normalizeArrayPath(value);
  if (ArrayBuffer.isView(value) && Object.getPrototypeOf(value) === Uint32Array.prototype) {
    return normalizeUint32ArrayPath(value as Uint32Array);
  }
  throw new TypeError("quox: DOM dispatch path must be a plain array or Uint32Array");
}

function recoverInitialFrameId(value: unknown): number | undefined {
  try {
    if (typeof value !== "object" || value === null) return undefined;
    const prototype = Object.getPrototypeOf(value);
    if (prototype !== Object.prototype && prototype !== null) return undefined;
    const descriptor = Object.getOwnPropertyDescriptor(value, "frameId");
    if (descriptor === undefined || !("value" in descriptor)) return undefined;
    return assertPositiveUint32(descriptor.value, "DOM dispatch frameId");
  } catch {
    return undefined;
  }
}

/** Validate an untrusted plain step object returned across the WASM boundary. */
export function validateDomDispatchStep(value: unknown): DomDispatchStep {
  const descriptors = inspectPlainRecord(value, "DOM dispatch step");
  const kind = requiredValue(descriptors, "kind", "DOM dispatch step");
  const frameId = assertPositiveUint32(
    requiredValue(descriptors, "frameId", "DOM dispatch step"),
    "DOM dispatch frameId",
  );

  if (kind === "complete") {
    return Object.freeze({
      kind,
      frameId,
      redrawRequested: assertBoolean(
        requiredValue(descriptors, "redrawRequested", "DOM dispatch step"),
        "DOM dispatch redrawRequested",
      ),
    });
  }
  if (kind !== "event") {
    throw new TypeError('quox: DOM dispatch step kind must be "event" or "complete"');
  }

  const target = assertPositiveUint32(
    requiredValue(descriptors, "target", "DOM dispatch step"),
    "DOM dispatch target",
  );
  const path = normalizePath(requiredValue(descriptors, "path", "DOM dispatch step"));
  if (path[0] !== target) {
    throw new RangeError("quox: DOM dispatch path must begin with its target");
  }

  const timeStamp = assertFiniteNumber(
    requiredValue(descriptors, "timeStamp", "DOM dispatch step"),
    "DOM dispatch timeStamp",
  );
  if (timeStamp < 0) {
    throw new RangeError("quox: DOM dispatch timeStamp must be nonnegative");
  }

  const step: DomDispatchEventStep = {
    kind,
    frameId,
    eventId: assertPositiveUint32(
      requiredValue(descriptors, "eventId", "DOM dispatch step"),
      "DOM dispatch eventId",
    ),
    type: assertEventType(requiredValue(descriptors, "type", "DOM dispatch step")),
    target,
    path,
    bubbles: assertBoolean(
      requiredValue(descriptors, "bubbles", "DOM dispatch step"),
      "DOM dispatch bubbles",
    ),
    cancelable: assertBoolean(
      requiredValue(descriptors, "cancelable", "DOM dispatch step"),
      "DOM dispatch cancelable",
    ),
    composed: assertBoolean(
      requiredValue(descriptors, "composed", "DOM dispatch step"),
      "DOM dispatch composed",
    ),
    timeStamp,
  };

  const payloadDescriptor = Object.getOwnPropertyDescriptor(descriptors, "payload");
  if (payloadDescriptor !== undefined) {
    const descriptor = payloadDescriptor.value as PropertyDescriptor;
    if (!("value" in descriptor)) {
      throw new TypeError("quox: DOM dispatch step.payload must not be an accessor");
    }
    return Object.freeze({ ...step, payload: descriptor.value });
  }
  return Object.freeze(step);
}

/** Typed and validated adapter over the staged methods absent from stale generated declarations. */
export class DomDispatchRendererPort {
  readonly #renderer: DomDispatchRendererSource;

  constructor(renderer: WasmRenderer | DomDispatchRendererSource) {
    this.#renderer = renderer as DomDispatchRendererSource;
  }

  #validateInitial(value: unknown): DomDispatchStep {
    try {
      return validateDomDispatchStep(value);
    } catch (error) {
      const frameId = recoverInitialFrameId(value);
      if (frameId === undefined) throw error;
      throw new DomDispatchInitialStepError(frameId, error);
    }
  }

  beginPointerMove(
    x: number,
    y: number,
    buttons: number,
    modifierBits: number,
    timeStamp: number,
  ): DomDispatchStep {
    return this.#validateInitial(
      this.#renderer.begin_pointer_move(x, y, buttons, modifierBits, timeStamp),
    );
  }

  beginPointerDown(
    x: number,
    y: number,
    button: number,
    buttons: number,
    modifierBits: number,
    timeStamp: number,
    detail: number,
  ): DomDispatchStep {
    return this.#validateInitial(
      this.#renderer.begin_pointer_down(
        x,
        y,
        button,
        buttons,
        modifierBits,
        timeStamp,
        detail,
      ),
    );
  }

  beginPointerUp(
    x: number,
    y: number,
    button: number,
    buttons: number,
    modifierBits: number,
    timeStamp: number,
    detail: number,
  ): DomDispatchStep {
    return this.#validateInitial(
      this.#renderer.begin_pointer_up(x, y, button, buttons, modifierBits, timeStamp, detail),
    );
  }

  beginWheel(
    x: number,
    y: number,
    blitzDeltaX: number,
    blitzDeltaY: number,
    deltaX: number,
    deltaY: number,
    deltaMode: number,
    buttons: number,
    modifierBits: number,
    timeStamp: number,
  ): DomDispatchStep {
    return this.#validateInitial(
      this.#renderer.begin_wheel(
        x,
        y,
        blitzDeltaX,
        blitzDeltaY,
        deltaX,
        deltaY,
        deltaMode,
        buttons,
        modifierBits,
        timeStamp,
      ),
    );
  }

  beginKeyEvent(
    code: string,
    key: string,
    keycode: number,
    modifierBits: number,
    location: number,
    eventFlags: number,
  ): DomDispatchStep {
    return this.#validateInitial(
      this.#renderer.begin_key_event(code, key, keycode, modifierBits, location, eventFlags),
    );
  }

  beginAppleStandardKeybinding(command: string): DomDispatchStep {
    return this.#validateInitial(this.#renderer.begin_apple_standard_keybinding(command));
  }

  beginImeEnabled(): DomDispatchStep {
    return this.#validateInitial(this.#renderer.begin_ime_enabled());
  }

  beginImeDisabled(): DomDispatchStep {
    return this.#validateInitial(this.#renderer.begin_ime_disabled());
  }

  beginImePreedit(text: string, cursorStart?: number, cursorEnd?: number): DomDispatchStep {
    return this.#validateInitial(
      this.#renderer.begin_ime_preedit(text, cursorStart, cursorEnd),
    );
  }

  beginImeCommit(text: string): DomDispatchStep {
    return this.#validateInitial(this.#renderer.begin_ime_commit(text));
  }

  beginImeDeleteSurrounding(beforeBytes: number, afterBytes: number): DomDispatchStep {
    return this.#validateInitial(
      this.#renderer.begin_ime_delete_surrounding(beforeBytes, afterBytes),
    );
  }

  resumeDomDispatch(
    frameId: number,
    eventId: number,
    defaultPrevented: boolean,
  ): DomDispatchStep {
    frameId = assertPositiveUint32(frameId, "DOM dispatch frameId");
    eventId = assertPositiveUint32(eventId, "DOM dispatch eventId");
    defaultPrevented = assertBoolean(defaultPrevented, "DOM dispatch defaultPrevented");
    const step = validateDomDispatchStep(
      this.#renderer.resume_dom_dispatch(frameId, eventId, defaultPrevented),
    );
    if (step.frameId !== frameId) {
      throw new RangeError("quox: resumed DOM dispatch step belongs to a different frame");
    }
    return step;
  }

  abortDomDispatch(frameId: number): boolean {
    const redrawRequested = this.#renderer.abort_dom_dispatch(
      assertPositiveUint32(frameId, "DOM dispatch frameId"),
    );
    return assertBoolean(redrawRequested, "DOM dispatch abort redrawRequested");
  }
}
