// Event type constants from X11/X.h
export enum XEventType {
  KeyPress = 2,
  KeyRelease = 3,
  ButtonPress = 4,
  ButtonRelease = 5,
  MotionNotify = 6,
  EnterNotify = 7,
  LeaveNotify = 8,
  FocusIn = 9,
  FocusOut = 10,
  KeymapNotify = 11,
  Expose = 12,
  GraphicsExpose = 13,
  NoExpose = 14,
  VisibilityNotify = 15,
  CreateNotify = 16,
  DestroyNotify = 17,
  UnmapNotify = 18,
  MapNotify = 19,
  MapRequest = 20,
  ReparentNotify = 21,
  ConfigureNotify = 22,
  ConfigureRequest = 23,
  GravityNotify = 24,
  ResizeRequest = 25,
  CirculateNotify = 26,
  CirculateRequest = 27,
  PropertyNotify = 28,
  SelectionClear = 29,
  SelectionRequest = 30,
  SelectionNotify = 31,
  ColormapNotify = 32,
  ClientMessage = 33,
  MappingNotify = 34,
  GenericEvent = 35,
  LASTEvent = 36,
}

// Event mask constants from X11/X.h
export enum XEventMask {
  NoEventMask = 0,
  KeyPressMask = 1 << 0,
  KeyReleaseMask = 1 << 1,
  ButtonPressMask = 1 << 2,
  ButtonReleaseMask = 1 << 3,
  EnterWindowMask = 1 << 4,
  LeaveWindowMask = 1 << 5,
  PointerMotionMask = 1 << 6,
  PointerMotionHintMask = 1 << 7,
  Button1MotionMask = 1 << 8,
  Button2MotionMask = 1 << 9,
  Button3MotionMask = 1 << 10,
  Button4MotionMask = 1 << 11,
  Button5MotionMask = 1 << 12,
  ButtonMotionMask = 1 << 13,
  KeymapStateMask = 1 << 14,
  ExposureMask = 1 << 15,
  VisibilityChangeMask = 1 << 16,
  StructureNotifyMask = 1 << 17,
  ResizeRedirectMask = 1 << 18,
  SubstructureNotifyMask = 1 << 19,
  SubstructureRedirectMask = 1 << 20,
  FocusChangeMask = 1 << 21,
  PropertyChangeMask = 1 << 22,
  ColormapChangeMask = 1 << 23,
  OwnerGrabButtonMask = 1 << 24,
}

// Function declarations from X11/Xlib.h
export const x11functions = {
  XActivateScreenSaver: { parameters: ["pointer"], result: "i32" },
  XAddConnectionWatch: { parameters: ["pointer", "pointer", "pointer"], result: "i32" },
  XAddExtension: { parameters: ["pointer"], result: "pointer" },
  XAddHost: { parameters: ["pointer", "pointer"], result: "i32" },
  XAddHosts: { parameters: ["pointer", "pointer", "i32"], result: "i32" },
  XAddToExtensionList: { parameters: ["pointer", "pointer"], result: "i32" },
  XAddToSaveSet: { parameters: ["pointer", "usize"], result: "i32" },
  XAllocColor: { parameters: ["pointer", "usize", "buffer"], result: "i32" },
  XAllocColorCells: { parameters: ["pointer", "usize", "i32", "pointer", "u32", "pointer", "u32"], result: "i32" },
  XAllocColorPlanes: {
    parameters: ["pointer", "usize", "i32", "pointer", "i32", "i32", "i32", "i32", "pointer", "pointer", "pointer"],
    result: "i32",
  },
  XAllocNamedColor: { parameters: ["pointer", "usize", "buffer", "buffer", "buffer"], result: "i32" },
  XAllPlanes: { parameters: [], result: "u64" },
  XAllowEvents: { parameters: ["pointer", "i32", "u64"], result: "i32" },
  XAutoRepeatOff: { parameters: ["pointer"], result: "i32" },
  XAutoRepeatOn: { parameters: ["pointer"], result: "i32" },
  XBaseFontNameListOfFontSet: { parameters: ["pointer"], result: "pointer" },
  XBell: { parameters: ["pointer", "i32"], result: "i32" },
  XBitmapBitOrder: { parameters: ["pointer"], result: "i32" },
  XBitmapPad: { parameters: ["pointer"], result: "i32" },
  XBitmapUnit: { parameters: ["pointer"], result: "i32" },
  XBlackPixel: { parameters: ["pointer", "i32"], result: "u64" },
  XBlackPixelOfScreen: { parameters: ["pointer"], result: "u64" },
  XCellsOfScreen: { parameters: ["pointer"], result: "i32" },
  XChangeActivePointerGrab: { parameters: ["pointer", "u32", "usize", "u64"], result: "i32" },
  XChangeGC: { parameters: ["pointer", "usize", "u64", "buffer"], result: "i32" },
  XChangeKeyboardControl: { parameters: ["pointer", "u64", "buffer"], result: "i32" },
  XChangeKeyboardMapping: { parameters: ["pointer", "i32", "i32", "pointer", "i32"], result: "i32" },
  XChangePointerControl: { parameters: ["pointer", "i32", "i32", "i32", "i32", "i32"], result: "i32" },
  XChangeProperty: { parameters: ["pointer", "usize", "usize", "usize", "i32", "i32", "buffer", "i32"], result: "i32" },
  XChangeSaveSet: { parameters: ["pointer", "usize", "i32"], result: "i32" },
  XChangeWindowAttributes: { parameters: ["pointer", "usize", "u64", "buffer"], result: "i32" },
  XCheckIfEvent: { parameters: ["pointer", "pointer", "pointer", "pointer"], result: "i32" },
  XCheckMaskEvent: { parameters: ["pointer", "i64", "pointer"], result: "i32" },
  XCheckTypedEvent: { parameters: ["pointer", "i32", "pointer"], result: "i32" },
  XCheckTypedWindowEvent: { parameters: ["pointer", "usize", "i32", "pointer"], result: "i32" },
  XCheckWindowEvent: { parameters: ["pointer", "usize", "i64", "pointer"], result: "i32" },
  XCirculateSubwindows: { parameters: ["pointer", "usize", "i32"], result: "i32" },
  XCirculateSubwindowsDown: { parameters: ["pointer", "usize"], result: "i32" },
  XCirculateSubwindowsUp: { parameters: ["pointer", "usize"], result: "i32" },
  XClearArea: { parameters: ["pointer", "usize", "i32", "i32", "u32", "u32", "i32"], result: "i32" },
  XClearWindow: { parameters: ["pointer", "usize"], result: "i32" },
  XCloseDisplay: { parameters: ["pointer"], result: "i32" },
  XCloseIM: { parameters: ["pointer"], result: "i32" },
  XCloseOM: { parameters: ["pointer"], result: "i32" },
  XConfigureWindow: { parameters: ["pointer", "usize", "u32", "buffer"], result: "i32" },
  XConnectionNumber: { parameters: ["pointer"], result: "i32" },
  XContextDependentDrawing: { parameters: ["pointer"], result: "i32" },
  XContextualDrawing: { parameters: ["pointer"], result: "i32" },
  XConvertSelection: { parameters: ["pointer", "usize", "usize", "usize", "usize", "u64"], result: "i32" },
  XCopyArea: {
    parameters: ["pointer", "usize", "usize", "usize", "i32", "i32", "u32", "u32", "i32", "i32"],
    result: "i32",
  },
  XCopyColormapAndFree: { parameters: ["pointer", "usize"], result: "usize" },
  XCopyGC: { parameters: ["pointer", "usize", "u64", "usize"], result: "i32" },
  XCopyPlane: {
    parameters: ["pointer", "usize", "usize", "usize", "i32", "i32", "u32", "u32", "i32", "i32", "u64"],
    result: "i32",
  },
  XCreateBitmapFromData: { parameters: ["pointer", "usize", "buffer", "u32", "u32"], result: "usize" },
  XCreateColormap: { parameters: ["pointer", "usize", "pointer", "i32"], result: "usize" },
  XCreateFontCursor: { parameters: ["pointer", "u32"], result: "usize" },
  XCreateFontSet: { parameters: ["pointer", "buffer", "pointer", "pointer", "pointer"], result: "pointer" },
  XCreateGC: { parameters: ["pointer", "usize", "u64", "buffer"], result: "usize" },
  XCreateGlyphCursor: { parameters: ["pointer", "usize", "usize", "u32", "u32", "buffer", "buffer"], result: "usize" },
  XCreateImage: {
    parameters: ["pointer", "pointer", "u32", "i32", "i32", "buffer", "u32", "u32", "i32", "i32"],
    result: "pointer",
  },
  XCreatePixmap: { parameters: ["pointer", "usize", "u32", "u32", "u32"], result: "usize" },
  XCreatePixmapCursor: { parameters: ["pointer", "usize", "usize", "buffer", "buffer", "u32", "u32"], result: "usize" },
  XCreatePixmapFromBitmapData: {
    parameters: ["pointer", "usize", "buffer", "u32", "u32", "u64", "u64", "u32"],
    result: "usize",
  },
  XCreateSimpleWindow: {
    parameters: ["pointer", "usize", "i32", "i32", "u32", "u32", "u32", "u64", "u64"],
    result: "usize",
  },
  XCreateWindow: {
    parameters: ["pointer", "usize", "i32", "i32", "u32", "u32", "u32", "i32", "u32", "pointer", "u64", "buffer"],
    result: "usize",
  },
  XDefaultColormap: { parameters: ["pointer", "i32"], result: "usize" },
  XDefaultColormapOfScreen: { parameters: ["pointer"], result: "usize" },
  XDefaultDepth: { parameters: ["pointer", "i32"], result: "i32" },
  XDefaultDepthOfScreen: { parameters: ["pointer"], result: "i32" },
  XDefaultGC: { parameters: ["pointer", "i32"], result: "usize" },
  XDefaultGCOfScreen: { parameters: ["pointer"], result: "usize" },
  XDefaultRootWindow: { parameters: ["pointer"], result: "usize" },
  XDefaultScreen: { parameters: ["pointer"], result: "i32" },
  XDefaultScreenOfDisplay: { parameters: ["pointer"], result: "pointer" },
  XDefaultVisual: { parameters: ["pointer", "i32"], result: "pointer" },
  XDefaultVisualOfScreen: { parameters: ["pointer"], result: "pointer" },
  XDefineCursor: { parameters: ["pointer", "usize", "usize"], result: "i32" },
  XDeleteModifiermapEntry: { parameters: ["pointer", "u32", "i32"], result: "pointer" },
  XDeleteProperty: { parameters: ["pointer", "usize", "usize"], result: "i32" },
  XDestroyIC: { parameters: ["pointer"], result: "void" },
  XDestroyOC: { parameters: ["pointer"], result: "void" },
  XDestroySubwindows: { parameters: ["pointer", "usize"], result: "i32" },
  XDestroyWindow: { parameters: ["pointer", "usize"], result: "i32" },
  XDirectionalDependentDrawing: { parameters: ["pointer"], result: "i32" },
  XDisableAccessControl: { parameters: ["pointer"], result: "i32" },
  XDisplayCells: { parameters: ["pointer", "i32"], result: "i32" },
  XDisplayHeight: { parameters: ["pointer", "i32"], result: "i32" },
  XDisplayHeightMM: { parameters: ["pointer", "i32"], result: "i32" },
  XDisplayKeycodes: { parameters: ["pointer", "pointer", "pointer"], result: "i32" },
  XDisplayName: { parameters: ["buffer"], result: "pointer" },
  XDisplayOfIM: { parameters: ["pointer"], result: "pointer" },
  XDisplayOfOM: { parameters: ["pointer"], result: "pointer" },
  XDisplayOfScreen: { parameters: ["pointer"], result: "pointer" },
  XDisplayPlanes: { parameters: ["pointer", "i32"], result: "i32" },
  XDisplayString: { parameters: ["pointer"], result: "pointer" },
  XDisplayWidth: { parameters: ["pointer", "i32"], result: "i32" },
  XDisplayWidthMM: { parameters: ["pointer", "i32"], result: "i32" },
  XDoesBackingStore: { parameters: ["pointer"], result: "i32" },
  XDoesSaveUnders: { parameters: ["pointer"], result: "i32" },
  XDrawArc: { parameters: ["pointer", "usize", "usize", "i32", "i32", "u32", "u32", "i32", "i32"], result: "i32" },
  XDrawArcs: { parameters: ["pointer", "usize", "usize", "buffer", "i32"], result: "i32" },
  XDrawImageString: { parameters: ["pointer", "usize", "usize", "i32", "i32", "buffer", "i32"], result: "i32" },
  XDrawImageString16: { parameters: ["pointer", "usize", "usize", "i32", "i32", "pointer", "i32"], result: "i32" },
  XDrawLine: { parameters: ["pointer", "usize", "usize", "i32", "i32", "i32", "i32"], result: "i32" },
  XDrawLines: { parameters: ["pointer", "usize", "usize", "buffer", "i32", "i32"], result: "i32" },
  XDrawPoint: { parameters: ["pointer", "usize", "usize", "i32", "i32"], result: "i32" },
  XDrawPoints: { parameters: ["pointer", "usize", "usize", "buffer", "i32", "i32"], result: "i32" },
  XDrawRectangle: { parameters: ["pointer", "usize", "usize", "i32", "i32", "u32", "u32"], result: "i32" },
  XDrawRectangles: { parameters: ["pointer", "usize", "usize", "buffer", "i32"], result: "i32" },
  XDrawSegments: { parameters: ["pointer", "usize", "usize", "buffer", "i32"], result: "i32" },
  XDrawString: { parameters: ["pointer", "usize", "usize", "i32", "i32", "buffer", "i32"], result: "i32" },
  XDrawString16: { parameters: ["pointer", "usize", "usize", "i32", "i32", "pointer", "i32"], result: "i32" },
  XDrawText: { parameters: ["pointer", "usize", "usize", "i32", "i32", "buffer", "i32"], result: "i32" },
  XDrawText16: { parameters: ["pointer", "usize", "usize", "i32", "i32", "buffer", "i32"], result: "i32" },
  XEnableAccessControl: { parameters: ["pointer"], result: "i32" },
  XEventMaskOfScreen: { parameters: ["pointer"], result: "i64" },
  XEventsQueued: { parameters: ["pointer", "i32"], result: "i32" },
  XExtendedMaxRequestSize: { parameters: ["pointer"], result: "i64" },
  XExtentsOfFontSet: { parameters: ["pointer"], result: "pointer" },
  XFetchBuffer: { parameters: ["pointer", "pointer", "i32"], result: "pointer" },
  XFetchBytes: { parameters: ["pointer", "pointer"], result: "pointer" },
  XFetchName: { parameters: ["pointer", "usize", "pointer"], result: "i32" },
  XFilterEvent: { parameters: ["pointer", "usize"], result: "i32" },
  XFillArc: { parameters: ["pointer", "usize", "usize", "i32", "i32", "u32", "u32", "i32", "i32"], result: "i32" },
  XFillArcs: { parameters: ["pointer", "usize", "usize", "buffer", "i32"], result: "i32" },
  XFillPolygon: { parameters: ["pointer", "usize", "usize", "buffer", "i32", "i32", "i32"], result: "i32" },
  XFillRectangle: { parameters: ["pointer", "usize", "usize", "i32", "i32", "u32", "u32"], result: "i32" },
  XFillRectangles: { parameters: ["pointer", "usize", "usize", "buffer", "i32"], result: "i32" },
  XFlush: { parameters: ["pointer"], result: "i32" },
  XFlushGC: { parameters: ["pointer", "usize"], result: "void" },
  XFontsOfFontSet: { parameters: ["pointer", "pointer", "pointer"], result: "i32" },
  XForceScreenSaver: { parameters: ["pointer", "i32"], result: "i32" },
  XFree: { parameters: ["pointer"], result: "i32" },
  XFreeColormap: { parameters: ["pointer", "usize"], result: "i32" },
  XFreeColors: { parameters: ["pointer", "usize", "buffer", "i32", "u64"], result: "i32" },
  XFreeCursor: { parameters: ["pointer", "usize"], result: "i32" },
  XFreeEventData: { parameters: ["pointer", "pointer"], result: "void" },
  XFreeExtensionList: { parameters: ["pointer"], result: "i32" },
  XFreeFont: { parameters: ["pointer", "pointer"], result: "i32" },
  XFreeFontInfo: { parameters: ["pointer", "pointer", "i32"], result: "i32" },
  XFreeFontNames: { parameters: ["pointer"], result: "i32" },
  XFreeFontPath: { parameters: ["pointer"], result: "i32" },
  XFreeFontSet: { parameters: ["pointer", "pointer"], result: "void" },
  XFreeGC: { parameters: ["pointer", "usize"], result: "i32" },
  XFreeModifiermap: { parameters: ["pointer"], result: "i32" },
  XFreePixmap: { parameters: ["pointer", "usize"], result: "i32" },
  XFreeStringList: { parameters: ["pointer"], result: "void" },
  XFreeThreads: { parameters: [], result: "i32" },
  XGContextFromGC: { parameters: ["usize"], result: "usize" },
  XGeometry: {
    parameters: [
      "pointer",
      "i32",
      "buffer",
      "buffer",
      "u32",
      "u32",
      "u32",
      "i32",
      "i32",
      "pointer",
      "pointer",
      "pointer",
      "pointer",
    ],
    result: "i32",
  },
  XGetAtomName: { parameters: ["pointer", "usize"], result: "pointer" },
  XGetAtomNames: { parameters: ["pointer", "buffer", "i32", "pointer"], result: "i32" },
  XGetCommand: { parameters: ["pointer", "usize", "pointer", "pointer"], result: "i32" },
  XGetDefault: { parameters: ["pointer", "buffer", "buffer"], result: "pointer" },
  XGetErrorDatabaseText: { parameters: ["pointer", "buffer", "buffer", "buffer", "pointer", "i32"], result: "i32" },
  XGetErrorText: { parameters: ["pointer", "i32", "pointer", "i32"], result: "i32" },
  XGetEventData: { parameters: ["pointer", "pointer"], result: "i32" },
  XGetFontPath: { parameters: ["pointer", "pointer"], result: "pointer" },
  XGetFontProperty: { parameters: ["pointer", "usize", "pointer"], result: "i32" },
  XGetGCValues: { parameters: ["pointer", "usize", "u64", "buffer"], result: "i32" },
  XGetGeometry: {
    parameters: ["pointer", "usize", "pointer", "pointer", "pointer", "pointer", "pointer", "pointer", "pointer"],
    result: "i32",
  },
  XGetIconName: { parameters: ["pointer", "usize", "pointer"], result: "i32" },
  XGetImage: { parameters: ["pointer", "usize", "i32", "i32", "u32", "u32", "u64", "i32"], result: "pointer" },
  XGetInputFocus: { parameters: ["pointer", "pointer", "pointer"], result: "i32" },
  XGetKeyboardControl: { parameters: ["pointer", "buffer"], result: "i32" },
  XGetKeyboardMapping: { parameters: ["pointer", "u32", "i32", "pointer"], result: "pointer" },
  XGetMotionEvents: { parameters: ["pointer", "usize", "u64", "u64", "pointer"], result: "pointer" },
  XGetPointerControl: { parameters: ["pointer", "pointer", "pointer", "pointer"], result: "i32" },
  XGetPointerMapping: { parameters: ["pointer", "pointer", "i32"], result: "i32" },
  XGetScreenSaver: { parameters: ["pointer", "pointer", "pointer", "pointer", "pointer"], result: "i32" },
  XGetSelectionOwner: { parameters: ["pointer", "usize"], result: "usize" },
  XGetSubImage: {
    parameters: ["pointer", "usize", "i32", "i32", "u32", "u32", "u64", "i32", "pointer", "i32", "i32"],
    result: "pointer",
  },
  XGetTransientForHint: { parameters: ["pointer", "usize", "pointer"], result: "i32" },
  XGetWMColormapWindows: { parameters: ["pointer", "usize", "pointer", "pointer"], result: "i32" },
  XGetWMProtocols: { parameters: ["pointer", "usize", "pointer", "pointer"], result: "i32" },
  XGetWindowAttributes: { parameters: ["pointer", "usize", "buffer"], result: "i32" },
  XGetWindowProperty: {
    parameters: [
      "pointer",
      "usize",
      "usize",
      "i64",
      "i64",
      "i32",
      "usize",
      "pointer",
      "pointer",
      "pointer",
      "pointer",
      "pointer",
    ],
    result: "i32",
  },
  XGrabButton: {
    parameters: ["pointer", "u32", "u32", "usize", "i32", "u32", "i32", "i32", "usize", "usize"],
    result: "i32",
  },
  XGrabKey: { parameters: ["pointer", "i32", "u32", "usize", "i32", "i32", "i32"], result: "i32" },
  XGrabKeyboard: { parameters: ["pointer", "usize", "i32", "i32", "i32", "u64"], result: "i32" },
  XGrabPointer: {
    parameters: ["pointer", "usize", "i32", "u32", "i32", "i32", "usize", "usize", "u64"],
    result: "i32",
  },
  XGrabServer: { parameters: ["pointer"], result: "i32" },
  XHeightMMOfScreen: { parameters: ["pointer"], result: "i32" },
  XHeightOfScreen: { parameters: ["pointer"], result: "i32" },
  XIconifyWindow: { parameters: ["pointer", "usize", "i32"], result: "i32" },
  XIfEvent: { parameters: ["pointer", "pointer", "pointer", "pointer"], result: "i32" },
  XImageByteOrder: { parameters: ["pointer"], result: "i32" },
  XIMOfIC: { parameters: ["pointer"], result: "pointer" },
  XInitExtension: { parameters: ["pointer", "buffer"], result: "pointer" },
  XInitImage: { parameters: ["pointer"], result: "i32" },
  XInitThreads: { parameters: [], result: "i32" },
  XInsertModifiermapEntry: { parameters: ["pointer", "u32", "i32"], result: "pointer" },
  XInstallColormap: { parameters: ["pointer", "usize"], result: "i32" },
  XInternAtom: { parameters: ["pointer", "buffer", "i32"], result: "usize" },
  XInternAtoms: { parameters: ["pointer", "pointer", "i32", "i32", "pointer"], result: "i32" },
  XInternalConnectionNumbers: { parameters: ["pointer", "pointer", "pointer"], result: "i32" },
  XKeycodeToKeysym: { parameters: ["pointer", "u32", "i32"], result: "usize" },
  XKeysymToKeycode: { parameters: ["pointer", "usize"], result: "u32" },
  XKeysymToString: { parameters: ["usize"], result: "pointer" },
  XKillClient: { parameters: ["pointer", "usize"], result: "i32" },
  XListDepths: { parameters: ["pointer", "i32", "pointer"], result: "pointer" },
  XListExtensions: { parameters: ["pointer", "pointer"], result: "pointer" },
  XListFonts: { parameters: ["pointer", "buffer", "i32", "pointer"], result: "pointer" },
  XListFontsWithInfo: { parameters: ["pointer", "buffer", "i32", "pointer", "pointer"], result: "pointer" },
  XListHosts: { parameters: ["pointer", "pointer", "pointer"], result: "pointer" },
  XListInstalledColormaps: { parameters: ["pointer", "usize", "pointer"], result: "pointer" },
  XListPixmapFormats: { parameters: ["pointer", "pointer"], result: "pointer" },
  XListProperties: { parameters: ["pointer", "usize", "pointer"], result: "pointer" },
  XLoadFont: { parameters: ["pointer", "buffer"], result: "usize" },
  XLoadQueryFont: { parameters: ["pointer", "buffer"], result: "pointer" },
  XLocaleOfFontSet: { parameters: ["pointer"], result: "pointer" },
  XLocaleOfIM: { parameters: ["pointer"], result: "pointer" },
  XLocaleOfOM: { parameters: ["pointer"], result: "pointer" },
  XLockDisplay: { parameters: ["pointer"], result: "void" },
  XLookupColor: { parameters: ["pointer", "usize", "buffer", "buffer", "buffer"], result: "i32" },
  XLookupKeysym: { parameters: ["pointer", "i32"], result: "usize" },
  XLowerWindow: { parameters: ["pointer", "usize"], result: "i32" },
  XMapRaised: { parameters: ["pointer", "usize"], result: "i32" },
  XMapSubwindows: { parameters: ["pointer", "usize"], result: "i32" },
  XMapWindow: { parameters: ["pointer", "usize"], result: "i32" },
  XMaskEvent: { parameters: ["pointer", "i64", "pointer"], result: "i32" },
  XMaxCmapsOfScreen: { parameters: ["pointer"], result: "i32" },
  XMaxRequestSize: { parameters: ["pointer"], result: "i64" },
  XmbDrawImageString: {
    parameters: ["pointer", "usize", "pointer", "usize", "i32", "i32", "buffer", "i32"],
    result: "void",
  },
  XmbDrawString: {
    parameters: ["pointer", "usize", "pointer", "usize", "i32", "i32", "buffer", "i32"],
    result: "void",
  },
  XmbDrawText: { parameters: ["pointer", "usize", "usize", "i32", "i32", "buffer", "i32"], result: "void" },
  XmbLookupString: { parameters: ["pointer", "pointer", "pointer", "i32", "pointer", "pointer"], result: "i32" },
  XmbResetIC: { parameters: ["pointer"], result: "pointer" },
  XmbTextEscapement: { parameters: ["pointer", "buffer", "i32"], result: "i32" },
  XmbTextExtents: { parameters: ["pointer", "buffer", "i32", "buffer", "buffer"], result: "i32" },
  XmbTextPerCharExtents: {
    parameters: ["pointer", "buffer", "i32", "buffer", "buffer", "i32", "pointer", "buffer", "buffer"],
    result: "i32",
  },
  XMinCmapsOfScreen: { parameters: ["pointer"], result: "i32" },
  XMoveResizeWindow: { parameters: ["pointer", "usize", "i32", "i32", "u32", "u32"], result: "i32" },
  XMoveWindow: { parameters: ["pointer", "usize", "i32", "i32"], result: "i32" },
  XNewModifiermap: { parameters: ["i32"], result: "pointer" },
  XNextEvent: { parameters: ["pointer", "pointer"], result: "i32" },
  XNextRequest: { parameters: ["pointer"], result: "u64" },
  XNoOp: { parameters: ["pointer"], result: "i32" },
  XOMOfOC: { parameters: ["pointer"], result: "pointer" },
  XOpenDisplay: { parameters: ["buffer"], result: "pointer" },
  XOpenIM: { parameters: ["pointer", "pointer", "buffer", "buffer"], result: "pointer" },
  XOpenOM: { parameters: ["pointer", "pointer", "buffer", "buffer"], result: "pointer" },
  XParseColor: { parameters: ["pointer", "usize", "buffer", "buffer"], result: "i32" },
  XParseGeometry: { parameters: ["buffer", "pointer", "pointer", "pointer", "pointer"], result: "i32" },
  XPeekEvent: { parameters: ["pointer", "pointer"], result: "i32" },
  XPeekIfEvent: { parameters: ["pointer", "pointer", "pointer", "pointer"], result: "i32" },
  XPending: { parameters: ["pointer"], result: "i32" },
  XPlanesOfScreen: { parameters: ["pointer"], result: "i32" },
  XProcessInternalConnection: { parameters: ["pointer", "i32"], result: "void" },
  XProtocolRevision: { parameters: ["pointer"], result: "i32" },
  XProtocolVersion: { parameters: ["pointer"], result: "i32" },
  XPutBackEvent: { parameters: ["pointer", "pointer"], result: "i32" },
  XPutImage: {
    parameters: ["pointer", "usize", "usize", "pointer", "i32", "i32", "i32", "i32", "u32", "u32"],
    result: "i32",
  },
  XQLength: { parameters: ["pointer"], result: "i32" },
  XQueryBestCursor: { parameters: ["pointer", "usize", "u32", "u32", "pointer", "pointer"], result: "i32" },
  XQueryBestSize: { parameters: ["pointer", "i32", "usize", "u32", "u32", "pointer", "pointer"], result: "i32" },
  XQueryBestStipple: { parameters: ["pointer", "usize", "u32", "u32", "pointer", "pointer"], result: "i32" },
  XQueryBestTile: { parameters: ["pointer", "usize", "u32", "u32", "pointer", "pointer"], result: "i32" },
  XQueryColor: { parameters: ["pointer", "usize", "buffer"], result: "i32" },
  XQueryColors: { parameters: ["pointer", "usize", "buffer", "i32"], result: "i32" },
  XQueryExtension: { parameters: ["pointer", "buffer", "pointer", "pointer", "pointer"], result: "i32" },
  XQueryFont: { parameters: ["pointer", "usize"], result: "pointer" },
  XQueryKeymap: { parameters: ["pointer", "buffer"], result: "i32" },
  XQueryPointer: {
    parameters: ["pointer", "usize", "pointer", "pointer", "pointer", "pointer", "pointer", "pointer", "pointer"],
    result: "i32",
  },
  XQueryTextExtents: {
    parameters: ["pointer", "usize", "buffer", "i32", "pointer", "pointer", "pointer", "buffer"],
    result: "i32",
  },
  XQueryTextExtents16: {
    parameters: ["pointer", "usize", "pointer", "i32", "pointer", "pointer", "pointer", "buffer"],
    result: "i32",
  },
  XQueryTree: { parameters: ["pointer", "usize", "pointer", "pointer", "pointer", "pointer"], result: "i32" },
  XRaiseWindow: { parameters: ["pointer", "usize"], result: "i32" },
  XReadBitmapFile: {
    parameters: ["pointer", "usize", "buffer", "pointer", "pointer", "pointer", "pointer", "pointer"],
    result: "i32",
  },
  XReadBitmapFileData: { parameters: ["buffer", "pointer", "pointer", "pointer", "pointer", "pointer"], result: "i32" },
  XRebindKeysym: { parameters: ["pointer", "usize", "pointer", "i32", "buffer", "i32"], result: "i32" },
  XRecolorCursor: { parameters: ["pointer", "usize", "buffer", "buffer"], result: "i32" },
  XReconfigureWMWindow: { parameters: ["pointer", "usize", "i32", "u32", "buffer"], result: "i32" },
  XRefreshKeyboardMapping: { parameters: ["pointer"], result: "i32" },
  XRegisterIMInstantiateCallback: {
    parameters: ["pointer", "pointer", "buffer", "buffer", "pointer", "pointer"],
    result: "i32",
  },
  XRemoveConnectionWatch: { parameters: ["pointer", "pointer", "pointer"], result: "void" },
  XRemoveFromSaveSet: { parameters: ["pointer", "usize"], result: "i32" },
  XRemoveHost: { parameters: ["pointer", "pointer"], result: "i32" },
  XRemoveHosts: { parameters: ["pointer", "pointer", "i32"], result: "i32" },
  XReparentWindow: { parameters: ["pointer", "usize", "usize", "i32", "i32"], result: "i32" },
  XResetScreenSaver: { parameters: ["pointer"], result: "i32" },
  XResizeWindow: { parameters: ["pointer", "usize", "u32", "u32"], result: "i32" },
  XResourceManagerString: { parameters: ["pointer"], result: "pointer" },
  XRestackWindows: { parameters: ["pointer", "buffer", "i32"], result: "i32" },
  XrmInitialize: { parameters: [], result: "void" },
  XRotateBuffers: { parameters: ["pointer", "i32"], result: "i32" },
  XRotateWindowProperties: { parameters: ["pointer", "usize", "buffer", "i32", "i32"], result: "i32" },
  XRootWindow: { parameters: ["pointer", "i32"], result: "usize" },
  XRootWindowOfScreen: { parameters: ["pointer"], result: "usize" },
  XScreenCount: { parameters: ["pointer"], result: "i32" },
  XScreenNumberOfScreen: { parameters: ["pointer"], result: "i32" },
  XScreenOfDisplay: { parameters: ["pointer", "i32"], result: "pointer" },
  XScreenResourceString: { parameters: ["pointer"], result: "pointer" },
  XSelectInput: { parameters: ["pointer", "usize", "i64"], result: "i32" },
  XSendEvent: { parameters: ["pointer", "usize", "i32", "i64", "pointer"], result: "i32" },
  XSetAccessControl: { parameters: ["pointer", "i32"], result: "i32" },
  XSetArcMode: { parameters: ["pointer", "usize", "i32"], result: "i32" },
  XSetAuthorization: { parameters: ["buffer", "i32", "buffer", "i32"], result: "void" },
  XSetBackground: { parameters: ["pointer", "usize", "u64"], result: "i32" },
  XSetClipMask: { parameters: ["pointer", "usize", "usize"], result: "i32" },
  XSetClipOrigin: { parameters: ["pointer", "usize", "i32", "i32"], result: "i32" },
  XSetClipRectangles: { parameters: ["pointer", "usize", "i32", "i32", "buffer", "i32", "i32"], result: "i32" },
  XSetCloseDownMode: { parameters: ["pointer", "i32"], result: "i32" },
  XSetCommand: { parameters: ["pointer", "usize", "pointer", "i32"], result: "i32" },
  XSetDashes: { parameters: ["pointer", "usize", "i32", "buffer", "i32"], result: "i32" },
  XSetErrorHandler: { parameters: ["pointer"], result: "pointer" },
  XSetFillRule: { parameters: ["pointer", "usize", "i32"], result: "i32" },
  XSetFillStyle: { parameters: ["pointer", "usize", "i32"], result: "i32" },
  XSetFont: { parameters: ["pointer", "usize", "usize"], result: "i32" },
  XSetFontPath: { parameters: ["pointer", "pointer", "i32"], result: "i32" },
  XSetForeground: { parameters: ["pointer", "usize", "u64"], result: "i32" },
  XSetFunction: { parameters: ["pointer", "usize", "i32"], result: "i32" },
  XSetGraphicsExposures: { parameters: ["pointer", "usize", "i32"], result: "i32" },
  XSetICFocus: { parameters: ["pointer"], result: "void" },
  XSetIconName: { parameters: ["pointer", "usize", "buffer"], result: "i32" },
  XSetInputFocus: { parameters: ["pointer", "usize", "i32", "u64"], result: "i32" },
  XSetIOErrorExitHandler: { parameters: ["pointer", "pointer", "pointer"], result: "void" },
  XSetIOErrorHandler: { parameters: ["pointer"], result: "pointer" },
  XSetLineAttributes: { parameters: ["pointer", "usize", "u32", "i32", "i32", "i32"], result: "i32" },
  XSetLocaleModifiers: { parameters: ["buffer"], result: "pointer" },
  XSetModifierMapping: { parameters: ["pointer", "pointer"], result: "i32" },
  XSetPlaneMask: { parameters: ["pointer", "usize", "u64"], result: "i32" },
  XSetPointerMapping: { parameters: ["pointer", "buffer", "i32"], result: "i32" },
  XSetScreenSaver: { parameters: ["pointer", "i32", "i32", "i32", "i32"], result: "i32" },
  XSetSelectionOwner: { parameters: ["pointer", "usize", "usize", "u64"], result: "i32" },
  XSetState: { parameters: ["pointer", "usize", "u64", "u64", "i32", "u64"], result: "i32" },
  XSetStipple: { parameters: ["pointer", "usize", "usize"], result: "i32" },
  XSetSubwindowMode: { parameters: ["pointer", "usize", "i32"], result: "i32" },
  XSetTSOrigin: { parameters: ["pointer", "usize", "i32", "i32"], result: "i32" },
  XSetTile: { parameters: ["pointer", "usize", "usize"], result: "i32" },
  XSetTransientForHint: { parameters: ["pointer", "usize", "usize"], result: "i32" },
  XSetWindowBackground: { parameters: ["pointer", "usize", "u64"], result: "i32" },
  XSetWindowBackgroundPixmap: { parameters: ["pointer", "usize", "usize"], result: "i32" },
  XSetWindowBorder: { parameters: ["pointer", "usize", "u64"], result: "i32" },
  XSetWindowBorderPixmap: { parameters: ["pointer", "usize", "usize"], result: "i32" },
  XSetWindowBorderWidth: { parameters: ["pointer", "usize", "u32"], result: "i32" },
  XSetWindowColormap: { parameters: ["pointer", "usize", "usize"], result: "i32" },
  XSetWMColormapWindows: { parameters: ["pointer", "usize", "buffer", "i32"], result: "i32" },
  XSetWMProtocols: { parameters: ["pointer", "usize", "buffer", "i32"], result: "i32" },
  XStoreBuffer: { parameters: ["pointer", "buffer", "i32", "i32"], result: "i32" },
  XStoreBytes: { parameters: ["pointer", "buffer", "i32"], result: "i32" },
  XStoreColor: { parameters: ["pointer", "usize", "buffer"], result: "i32" },
  XStoreColors: { parameters: ["pointer", "usize", "buffer", "i32"], result: "i32" },
  XStoreName: { parameters: ["pointer", "usize", "buffer"], result: "i32" },
  XStoreNamedColor: { parameters: ["pointer", "usize", "buffer", "u64", "i32"], result: "i32" },
  XStringToKeysym: { parameters: ["buffer"], result: "usize" },
  XSupportsLocale: { parameters: [], result: "i32" },
  XSync: { parameters: ["pointer", "i32"], result: "i32" },
  XSynchronize: { parameters: ["pointer", "i32"], result: "pointer" },
  XTextExtents: { parameters: ["pointer", "buffer", "i32", "pointer", "pointer", "pointer", "buffer"], result: "i32" },
  XTextExtents16: {
    parameters: ["pointer", "pointer", "i32", "pointer", "pointer", "pointer", "buffer"],
    result: "i32",
  },
  XTextWidth: { parameters: ["pointer", "buffer", "i32"], result: "i32" },
  XTextWidth16: { parameters: ["pointer", "pointer", "i32"], result: "i32" },
  XTranslateCoordinates: {
    parameters: ["pointer", "usize", "usize", "i32", "i32", "pointer", "pointer", "pointer"],
    result: "i32",
  },
  XUndefineCursor: { parameters: ["pointer", "usize"], result: "i32" },
  XUngrabButton: { parameters: ["pointer", "u32", "u32", "usize"], result: "i32" },
  XUngrabKey: { parameters: ["pointer", "i32", "u32", "usize"], result: "i32" },
  XUngrabKeyboard: { parameters: ["pointer", "u64"], result: "i32" },
  XUngrabPointer: { parameters: ["pointer", "u64"], result: "i32" },
  XUngrabServer: { parameters: ["pointer"], result: "i32" },
  XUninstallColormap: { parameters: ["pointer", "usize"], result: "i32" },
  XUnloadFont: { parameters: ["pointer", "usize"], result: "i32" },
  XUnlockDisplay: { parameters: ["pointer"], result: "void" },
  XUnmapSubwindows: { parameters: ["pointer", "usize"], result: "i32" },
  XUnmapWindow: { parameters: ["pointer", "usize"], result: "i32" },
  XUnregisterIMInstantiateCallback: {
    parameters: ["pointer", "pointer", "buffer", "buffer", "pointer", "pointer"],
    result: "i32",
  },
  XUnsetICFocus: { parameters: ["pointer"], result: "void" },
  XVendorRelease: { parameters: ["pointer"], result: "i32" },
  XVisualIDFromVisual: { parameters: ["pointer"], result: "usize" },
  XWarpPointer: {
    parameters: ["pointer", "usize", "usize", "i32", "i32", "u32", "u32", "i32", "i32"],
    result: "i32",
  },
  XWhitePixel: { parameters: ["pointer", "i32"], result: "u64" },
  XWhitePixelOfScreen: { parameters: ["pointer"], result: "u64" },
  XWidthMMOfScreen: { parameters: ["pointer"], result: "i32" },
  XWidthOfScreen: { parameters: ["pointer"], result: "i32" },
  XWindowEvent: { parameters: ["pointer", "usize", "i64", "pointer"], result: "i32" },
  XWithdrawWindow: { parameters: ["pointer", "usize", "i32"], result: "i32" },
  XWriteBitmapFile: { parameters: ["pointer", "buffer", "usize", "u32", "u32", "i32", "i32"], result: "i32" },
  XwcDrawImageString: {
    parameters: ["pointer", "usize", "pointer", "usize", "i32", "i32", "pointer", "i32"],
    result: "void",
  },
  XwcDrawString: {
    parameters: ["pointer", "usize", "pointer", "usize", "i32", "i32", "pointer", "i32"],
    result: "void",
  },
  XwcDrawText: { parameters: ["pointer", "usize", "usize", "i32", "i32", "buffer", "i32"], result: "void" },
  XwcLookupString: { parameters: ["pointer", "pointer", "pointer", "i32", "pointer", "pointer"], result: "i32" },
  XwcResetIC: { parameters: ["pointer"], result: "pointer" },
  XwcTextEscapement: { parameters: ["pointer", "pointer", "i32"], result: "i32" },
  XwcTextExtents: { parameters: ["pointer", "pointer", "i32", "buffer", "buffer"], result: "i32" },
  XwcTextPerCharExtents: {
    parameters: ["pointer", "pointer", "i32", "buffer", "buffer", "i32", "pointer", "buffer", "buffer"],
    result: "i32",
  },
  Xutf8DrawImageString: {
    parameters: ["pointer", "usize", "pointer", "usize", "i32", "i32", "buffer", "i32"],
    result: "void",
  },
  Xutf8DrawString: {
    parameters: ["pointer", "usize", "pointer", "usize", "i32", "i32", "buffer", "i32"],
    result: "void",
  },
  Xutf8DrawText: { parameters: ["pointer", "usize", "usize", "i32", "i32", "buffer", "i32"], result: "void" },
  Xutf8LookupString: { parameters: ["pointer", "pointer", "pointer", "i32", "pointer", "pointer"], result: "i32" },
  Xutf8ResetIC: { parameters: ["pointer"], result: "pointer" },
  Xutf8TextEscapement: { parameters: ["pointer", "buffer", "i32"], result: "i32" },
  Xutf8TextExtents: { parameters: ["pointer", "buffer", "i32", "buffer", "buffer"], result: "i32" },
  Xutf8TextPerCharExtents: {
    parameters: ["pointer", "buffer", "i32", "buffer", "buffer", "i32", "pointer", "buffer", "buffer"],
    result: "i32",
  },
} as const satisfies Deno.ForeignLibraryInterface;
