name: check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: denoland/setup-deno@v2
      - run: deno fmt --check
      - run: deno lint
      - run: deno task build:prod
      - run: deno check
      - run: deno publish --dry-run

  publish:
    needs: check
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - uses: denoland/setup-deno@v2
      - run: deno task build:prod
      - run: deno publish
